## Wrapper around `zwp_tablet_pad_dial_v2` (`TabletPadDial`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  TabletPadDialObj* = object
    handle*: ptr zwp_tablet_pad_dial_v2
    payload: TabletPadDialPayload

  TabletPadDial* = ref TabletPadDialObj
    ## =====
    ## pad dial
    ## =====
    ## A rotary control, e.g. a dial or a wheel. Events on a dial are logically grouped by the zwp_tablet_pad_dial_v2.frame event.

  TabletPadDialDeltaCallback* = proc(value120: int32)
  TabletPadDialFrameCallback* = proc(time: uint32)
  TabletPadDialPayload = ref object
    deltaCb: TabletPadDialDeltaCallback
    frameCb: TabletPadDialFrameCallback


proc `=destroy`*(obj: TabletPadDialObj) =
  ## =====
  ## destroy the dial object
  ## =====
  ## This destroys the client's resource for this dial object.
  zwp_tablet_pad_dial_v2_destroy(obj.handle)


# wrapgen: begin emitting constructor routines
func initTabletPadDial*(raw: ptr zwp_tablet_pad_dial_v2 | pointer): TabletPadDial =
  ## Instantiate a TabletPadDial using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTabletPadDial() was given an uninitialized handle!")
  
  TabletPadDial(handle: cast[ptr zwp_tablet_pad_dial_v2](raw), payload: TabletPadDialPayload())

func newTabletPadDial*(raw: ptr zwp_tablet_pad_dial_v2): TabletPadDial =
  ## Instantiate a TabletPadDial using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTabletPadDial() was given an uninitialized handle!")
  
  TabletPadDial(handle: raw, payload: TabletPadDialPayload())

# wrapgen: end emitting constructor routines


let listener {.global.} =
  zwp_tablet_pad_dial_v2_listener(
    delta: proc(data: pointer, this: ptr zwp_tablet_pad_dial_v2, value120: int32) {.cdecl.} =
      let payload = cast[TabletPadDialPayload](data)
      if payload.deltaCb == nil:
        write(stderr, "[nayland] handler not attached for event 'delta'!\n")
        return

      payload.deltaCb(value120)  ,    frame: proc(data: pointer, this: ptr zwp_tablet_pad_dial_v2, time: uint32) {.cdecl.} =
      let payload = cast[TabletPadDialPayload](data)
      if payload.frameCb == nil:
        write(stderr, "[nayland] handler not attached for event 'frame'!\n")
        return

      payload.frameCb(time)
)
proc attachCallbacks*(obj: TabletPadDial) =
  discard zwp_tablet_pad_dial_v2_add_listener(obj.handle, listener.addr, cast[pointer](obj.payload))

func `onDelta=`*(obj: TabletPadDial, cb: TabletPadDialDeltaCallback) {.inline, raises: [].} =
  obj.payload.deltaCb = cb
func `onFrame=`*(obj: TabletPadDial, cb: TabletPadDialFrameCallback) {.inline, raises: [].} =
  obj.payload.frameCb = cb

# wrapgen: start emitting request wrappers

proc setFeedback*(obj: TabletPadDial, Description: cstring, Serial: uint32) =
  ## =====
  ## set compositor feedback
  ## =====
  ## Requests the compositor to use the provided feedback string associated with this dial. This request should be issued immediately after a zwp_tablet_pad_group_v2.mode_switch event from the corresponding group is received, or whenever the dial is mapped to a different action. See zwp_tablet_pad_group_v2.mode_switch for more details. Clients are encouraged to provide context-aware descriptions for the actions associated with the dial, and compositors may use this information to offer visual feedback about the button layout (eg. on-screen displays). The provided string 'description' is a UTF-8 encoded string to be associated with this ring, and is considered user-visible; general internationalization rules apply. The serial argument will be that of the last zwp_tablet_pad_group_v2.mode_switch event received for the group of this dial. Requests providing other serials than the most recent one will be ignored.
  zwp_tablet_pad_dial_v2_set_feedback(obj.handle, Description, Serial)



# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
