## Wrapper around `zwp_tablet_pad_dial_v2` (`TabletPadDial`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  TabletPadDialObj* = object
    handle*: ptr zwp_tablet_pad_dial_v2

  TabletPadDial* = ref TabletPadDialObj
    ## =====
    ## end of a dial event sequence
    ## =====
    ## Indicates the end of a set of events that represent one logical hardware dial event. A client is expected to accumulate the data in all events within the frame before proceeding. All zwp_tablet_pad_dial_v2 events before a zwp_tablet_pad_dial_v2.frame event belong logically together. A zwp_tablet_pad_dial_v2.frame event is sent for every logical event group, even if the group only contains a single zwp_tablet_pad_dial_v2 event. Specifically, a client may get a sequence: delta, frame, delta, frame, etc.

# wrapgen: end emitting interface structures
# wrapgen: start emitting request wrappers

proc setFeedback*(obj: TabletPadDial, Description: string, Serial: uint32) =
  ## =====
  ## set compositor feedback
  ## =====
  ## Requests the compositor to use the provided feedback string associated with this dial. This request should be issued immediately after a zwp_tablet_pad_group_v2.mode_switch event from the corresponding group is received, or whenever the dial is mapped to a different action. See zwp_tablet_pad_group_v2.mode_switch for more details. Clients are encouraged to provide context-aware descriptions for the actions associated with the dial, and compositors may use this information to offer visual feedback about the button layout (eg. on-screen displays). The provided string 'description' is a UTF-8 encoded string to be associated with this ring, and is considered user-visible; general internationalization rules apply. The serial argument will be that of the last zwp_tablet_pad_group_v2.mode_switch event received for the group of this dial. Requests providing other serials than the most recent one will be ignored.
  zwp_tablet_pad_dial_v2_set_feedback(obj.handle, Description, Serial)

proc `=destroy`*(obj: TabletPadDialObj) =
  ## =====
  ## destroy the dial object
  ## =====
  ## This destroys the client's resource for this dial object.
  zwp_tablet_pad_dial_v2_destroy(obj.handle)



# wrapgen: end emitting request wrappers
# wrapgen: begin emitting constructor routines
func initTabletPadDial*(raw: ptr zwp_tablet_pad_dial_v2 | pointer): TabletPadDial =
  ## Instantiate a TabletPadDial using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTabletPadDial() was given an uninitialized handle!")
  
  TabletPadDial(handle: cast[ptr zwp_tablet_pad_dial_v2](raw))

func newTabletPadDial*(raw: ptr zwp_tablet_pad_dial_v2): TabletPadDial =
  ## Instantiate a TabletPadDial using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTabletPadDial() was given an uninitialized handle!")
  
  TabletPadDial(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
