## Wrapper around `zwp_tablet_pad_group_v2` (`TabletPadGroup`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  TabletPadGroupObj* = object
    handle*: ptr zwp_tablet_pad_group_v2

  TabletPadGroup* = ref TabletPadGroupObj
    ## =====
    ## dial announced
    ## =====
    ## Sent on zwp_tablet_pad_v2 initialization to announce available dials. One event is sent for each dial available on this pad group. This event is sent in the initial burst of events before the zwp_tablet_pad_group_v2.done event.

# wrapgen: end emitting interface structures
# wrapgen: start emitting request wrappers
proc `=destroy`*(obj: TabletPadGroupObj) =
  ## =====
  ## destroy the pad object
  ## =====
  ## Destroy the zwp_tablet_pad_group_v2 object. Objects created from this object are unaffected and should be destroyed separately.
  zwp_tablet_pad_group_v2_destroy(obj.handle)



# wrapgen: end emitting request wrappers
# wrapgen: begin emitting constructor routines
func initTabletPadGroup*(raw: ptr zwp_tablet_pad_group_v2 | pointer): TabletPadGroup =
  ## Instantiate a TabletPadGroup using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTabletPadGroup() was given an uninitialized handle!")
  
  TabletPadGroup(handle: cast[ptr zwp_tablet_pad_group_v2](raw))

func newTabletPadGroup*(raw: ptr zwp_tablet_pad_group_v2): TabletPadGroup =
  ## Instantiate a TabletPadGroup using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTabletPadGroup() was given an uninitialized handle!")
  
  TabletPadGroup(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
