## Wrapper around `zwp_tablet_pad_v2` (`TabletPad`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Button_state* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## physical button state
    ## =====
    ## Describes the physical state of a button that caused the button event.
    Released = 0'u32 ## the button is not pressed
    Pressed = 1'u32 ## the button is pressed

  TabletPadObj* = object
    handle*: ptr zwp_tablet_pad_v2

  TabletPad* = ref TabletPadObj
    ## =====
    ## pad removed event
    ## =====
    ## Sent when the pad has been removed from the system. When a tablet is removed its pad(s) will be removed too. When this event is received, the client must destroy all rings, strips and groups that were offered by this pad, and issue zwp_tablet_pad_v2.destroy the pad itself.

# wrapgen: end emitting interface structures
# wrapgen: start emitting request wrappers

proc setFeedback*(obj: TabletPad, Button: uint32, Description: string, Serial: uint32) =
  ## =====
  ## set compositor feedback
  ## =====
  ## Requests the compositor to use the provided feedback string associated with this button. This request should be issued immediately after a zwp_tablet_pad_group_v2.mode_switch event from the corresponding group is received, or whenever a button is mapped to a different action. See zwp_tablet_pad_group_v2.mode_switch for more details. Clients are encouraged to provide context-aware descriptions for the actions associated with each button, and compositors may use this information to offer visual feedback on the button layout (e.g. on-screen displays). Button indices start at 0. Setting the feedback string on a button that is reserved by the compositor (i.e. not belonging to any zwp_tablet_pad_group_v2) does not generate an error but the compositor is free to ignore the request. The provided string 'description' is a UTF-8 encoded string to be associated with this ring, and is considered user-visible; general internationalization rules apply. The serial argument will be that of the last zwp_tablet_pad_group_v2.mode_switch event received for the group of this button. Requests providing other serials than the most recent one will be ignored.
  zwp_tablet_pad_v2_set_feedback(obj.handle, Button, Description, Serial)

proc `=destroy`*(obj: TabletPadObj) =
  ## =====
  ## destroy the pad object
  ## =====
  ## Destroy the zwp_tablet_pad_v2 object. Objects created from this object are unaffected and should be destroyed separately.
  zwp_tablet_pad_v2_destroy(obj.handle)



# wrapgen: end emitting request wrappers
# wrapgen: begin emitting constructor routines
func initTabletPad*(raw: ptr zwp_tablet_pad_v2 | pointer): TabletPad =
  ## Instantiate a TabletPad using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTabletPad() was given an uninitialized handle!")
  
  TabletPad(handle: cast[ptr zwp_tablet_pad_v2](raw))

func newTabletPad*(raw: ptr zwp_tablet_pad_v2): TabletPad =
  ## Instantiate a TabletPad using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTabletPad() was given an uninitialized handle!")
  
  TabletPad(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting enum shims
converter shim0*(v: Button_state): uint32 = cast[uint32](v)
# wrapgen: end emitting enum shims
