import pkg/nayland/types/protocols/tablet/manager
export manager
import pkg/nayland/types/protocols/tablet/seat
export seat
import pkg/nayland/types/protocols/tablet/tool
export tool
import pkg/nayland/types/protocols/tablet/tablet
export tablet
import pkg/nayland/types/protocols/tablet/ring
export ring
import pkg/nayland/types/protocols/tablet/strip
export strip
import pkg/nayland/types/protocols/tablet/group
export group
import pkg/nayland/types/protocols/tablet/pad
export pad
import pkg/nayland/types/protocols/tablet/dial
export dial
