## Wrapper around `zwp_tablet_pad_ring_v2` (`TabletPadRing`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Source* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## ring axis source
    ## =====
    ## Describes the source types for ring events. This indicates to the client how a ring event was physically generated; a client may adjust the user interface accordingly. For example, events from a "finger" source may trigger kinetic scrolling.
    Finger = 1'u32 ## finger

  TabletPadRingObj* = object
    handle*: ptr zwp_tablet_pad_ring_v2
    payload: TabletPadRingPayload

  TabletPadRing* = ref TabletPadRingObj
    ## =====
    ## pad ring
    ## =====
    ## A circular interaction area, such as the touch ring on the Wacom Intuos Pro series tablets. Events on a ring are logically grouped by the zwp_tablet_pad_ring_v2.frame event.

  TabletPadRingSourceCallback* = proc(source: uint32)
  TabletPadRingAngleCallback* = proc(degrees: float)
  TabletPadRingStopCallback* = proc()
  TabletPadRingFrameCallback* = proc(time: uint32)
  TabletPadRingPayload = ref object
    sourceCb: TabletPadRingSourceCallback
    angleCb: TabletPadRingAngleCallback
    stopCb: TabletPadRingStopCallback
    frameCb: TabletPadRingFrameCallback


proc `=destroy`*(obj: TabletPadRingObj) =
  ## =====
  ## destroy the ring object
  ## =====
  ## This destroys the client's resource for this ring object.
  zwp_tablet_pad_ring_v2_destroy(obj.handle)


# wrapgen: begin emitting constructor routines
func initTabletPadRing*(raw: ptr zwp_tablet_pad_ring_v2 | pointer): TabletPadRing =
  ## Instantiate a TabletPadRing using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTabletPadRing() was given an uninitialized handle!")
  
  TabletPadRing(handle: cast[ptr zwp_tablet_pad_ring_v2](raw), payload: TabletPadRingPayload())

func newTabletPadRing*(raw: ptr zwp_tablet_pad_ring_v2): TabletPadRing =
  ## Instantiate a TabletPadRing using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTabletPadRing() was given an uninitialized handle!")
  
  TabletPadRing(handle: raw, payload: TabletPadRingPayload())

# wrapgen: end emitting constructor routines


let listener {.global.} =
  zwp_tablet_pad_ring_v2_listener(
    source: proc(data: pointer, this: ptr zwp_tablet_pad_ring_v2, source: uint32) {.cdecl.} =
      let payload = cast[TabletPadRingPayload](data)
      if payload.sourceCb == nil:
        write(stderr, "[nayland] handler not attached for event 'source'!\n")
        return

      payload.sourceCb(source)  ,    angle: proc(data: pointer, this: ptr zwp_tablet_pad_ring_v2, degrees: wl_fixed) {.cdecl.} =
      let payload = cast[TabletPadRingPayload](data)
      if payload.angleCb == nil:
        write(stderr, "[nayland] handler not attached for event 'angle'!\n")
        return

      payload.angleCb(degrees.toFloat)  ,    stop: proc(data: pointer, this: ptr zwp_tablet_pad_ring_v2) {.cdecl.} =
      let payload = cast[TabletPadRingPayload](data)
      if payload.stopCb == nil:
        write(stderr, "[nayland] handler not attached for event 'stop'!\n")
        return

      payload.stopCb()  ,    frame: proc(data: pointer, this: ptr zwp_tablet_pad_ring_v2, time: uint32) {.cdecl.} =
      let payload = cast[TabletPadRingPayload](data)
      if payload.frameCb == nil:
        write(stderr, "[nayland] handler not attached for event 'frame'!\n")
        return

      payload.frameCb(time)
)
proc attachCallbacks*(obj: TabletPadRing) =
  discard zwp_tablet_pad_ring_v2_add_listener(obj.handle, listener.addr, cast[pointer](obj.payload))

func `onSource=`*(obj: TabletPadRing, cb: TabletPadRingSourceCallback) {.inline, raises: [].} =
  obj.payload.sourceCb = cb
func `onAngle=`*(obj: TabletPadRing, cb: TabletPadRingAngleCallback) {.inline, raises: [].} =
  obj.payload.angleCb = cb
func `onStop=`*(obj: TabletPadRing, cb: TabletPadRingStopCallback) {.inline, raises: [].} =
  obj.payload.stopCb = cb
func `onFrame=`*(obj: TabletPadRing, cb: TabletPadRingFrameCallback) {.inline, raises: [].} =
  obj.payload.frameCb = cb

# wrapgen: start emitting request wrappers

proc setFeedback*(obj: TabletPadRing, Description: cstring, Serial: uint32) =
  ## =====
  ## set compositor feedback
  ## =====
  ## Request that the compositor use the provided feedback string associated with this ring. This request should be issued immediately after a zwp_tablet_pad_group_v2.mode_switch event from the corresponding group is received, or whenever the ring is mapped to a different action. See zwp_tablet_pad_group_v2.mode_switch for more details. Clients are encouraged to provide context-aware descriptions for the actions associated with the ring; compositors may use this information to offer visual feedback about the button layout (eg. on-screen displays). The provided string 'description' is a UTF-8 encoded string to be associated with this ring, and is considered user-visible; general internationalization rules apply. The serial argument will be that of the last zwp_tablet_pad_group_v2.mode_switch event received for the group of this ring. Requests providing other serials than the most recent one will be ignored.
  zwp_tablet_pad_ring_v2_set_feedback(obj.handle, Description, Serial)



# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Source): uint32 = cast[uint32](v)
# wrapgen: end emitting enum shims
