## Wrapper around `zwp_tablet_pad_ring_v2` (`TabletPadRing`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Source* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## ring axis source
    ## =====
    ## Describes the source types for ring events. This indicates to the client how a ring event was physically generated; a client may adjust the user interface accordingly. For example, events from a "finger" source may trigger kinetic scrolling.
    Finger = 1'u32 ## finger

  TabletPadRingObj* = object
    handle*: ptr zwp_tablet_pad_ring_v2

  TabletPadRing* = ref TabletPadRingObj
    ## =====
    ## end of a ring event sequence
    ## =====
    ## Indicates the end of a set of ring events that logically belong together. A client is expected to accumulate the data in all events within the frame before proceeding. All zwp_tablet_pad_ring_v2 events before a zwp_tablet_pad_ring_v2.frame event belong logically together. For example, on termination of a finger interaction on a ring the compositor will send a zwp_tablet_pad_ring_v2.source event, a zwp_tablet_pad_ring_v2.stop event and a zwp_tablet_pad_ring_v2.frame event. A zwp_tablet_pad_ring_v2.frame event is sent for every logical event group, even if the group only contains a single zwp_tablet_pad_ring_v2 event. Specifically, a client may get a sequence: angle, frame, angle, frame, etc.

# wrapgen: end emitting interface structures
# wrapgen: start emitting request wrappers

proc setFeedback*(obj: TabletPadRing, Description: string, Serial: uint32) =
  ## =====
  ## set compositor feedback
  ## =====
  ## Request that the compositor use the provided feedback string associated with this ring. This request should be issued immediately after a zwp_tablet_pad_group_v2.mode_switch event from the corresponding group is received, or whenever the ring is mapped to a different action. See zwp_tablet_pad_group_v2.mode_switch for more details. Clients are encouraged to provide context-aware descriptions for the actions associated with the ring; compositors may use this information to offer visual feedback about the button layout (eg. on-screen displays). The provided string 'description' is a UTF-8 encoded string to be associated with this ring, and is considered user-visible; general internationalization rules apply. The serial argument will be that of the last zwp_tablet_pad_group_v2.mode_switch event received for the group of this ring. Requests providing other serials than the most recent one will be ignored.
  zwp_tablet_pad_ring_v2_set_feedback(obj.handle, Description, Serial)

proc `=destroy`*(obj: TabletPadRingObj) =
  ## =====
  ## destroy the ring object
  ## =====
  ## This destroys the client's resource for this ring object.
  zwp_tablet_pad_ring_v2_destroy(obj.handle)



# wrapgen: end emitting request wrappers
# wrapgen: begin emitting constructor routines
func initTabletPadRing*(raw: ptr zwp_tablet_pad_ring_v2 | pointer): TabletPadRing =
  ## Instantiate a TabletPadRing using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTabletPadRing() was given an uninitialized handle!")
  
  TabletPadRing(handle: cast[ptr zwp_tablet_pad_ring_v2](raw))

func newTabletPadRing*(raw: ptr zwp_tablet_pad_ring_v2): TabletPadRing =
  ## Instantiate a TabletPadRing using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTabletPadRing() was given an uninitialized handle!")
  
  TabletPadRing(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting enum shims
converter shim0*(v: Source): uint32 = cast[uint32](v)
# wrapgen: end emitting enum shims
