## Wrapper around `zwp_tablet_seat_v2` (`TabletSeat`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  TabletSeatObj* = object
    handle*: ptr zwp_tablet_seat_v2

  TabletSeat* = ref TabletSeatObj
    ## =====
    ## new pad notification
    ## =====
    ## This event is sent whenever a new pad is known to the system. Typically, pads are physically attached to tablets and a pad_added event is sent immediately after the zwp_tablet_seat_v2.tablet_added. However, some standalone pad devices logically attach to tablets at runtime, and the client must wait for zwp_tablet_pad_v2.enter to know the tablet a pad is attached to. This event only provides the object id of the pad. All further features (buttons, strips, rings) are sent through the zwp_tablet_pad_v2 interface.

# wrapgen: end emitting interface structures
# wrapgen: start emitting request wrappers
proc `=destroy`*(obj: TabletSeatObj) =
  ## =====
  ## release the memory for the tablet seat object
  ## =====
  ## Destroy the zwp_tablet_seat_v2 object. Objects created from this object are unaffected and should be destroyed separately.
  zwp_tablet_seat_v2_destroy(obj.handle)



# wrapgen: end emitting request wrappers
# wrapgen: begin emitting constructor routines
func initTabletSeat*(raw: ptr zwp_tablet_seat_v2 | pointer): TabletSeat =
  ## Instantiate a TabletSeat using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTabletSeat() was given an uninitialized handle!")
  
  TabletSeat(handle: cast[ptr zwp_tablet_seat_v2](raw))

func newTabletSeat*(raw: ptr zwp_tablet_seat_v2): TabletSeat =
  ## Instantiate a TabletSeat using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTabletSeat() was given an uninitialized handle!")
  
  TabletSeat(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
