## Wrapper around `zwp_tablet_seat_v2` (`TabletSeat`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
import pkg/nayland/types/protocols/tablet/[pad, tablet, tool]
# wrapgen: begin emitting interface structures
type
  TabletSeatObj* = object
    handle*: ptr zwp_tablet_seat_v2
    payload: TabletSeatPayload

  TabletSeat* = ref TabletSeatObj
    ## =====
    ## controller object for graphic tablet devices of a seat
    ## =====
    ## An object that provides access to the graphics tablets available on this seat. After binding to this interface, the compositor sends a set of zwp_tablet_seat_v2.tablet_added and zwp_tablet_seat_v2.tool_added events.

  TabletSeatTabletAddedCallback* = proc(id: Tablet)
  TabletSeatToolAddedCallback* = proc(id: TabletTool)
  TabletSeatPadAddedCallback* = proc(id: TabletPad)
  TabletSeatPayload = ref object
    tablet_addedCb: TabletSeatTabletAddedCallback
    tool_addedCb: TabletSeatToolAddedCallback
    pad_addedCb: TabletSeatPadAddedCallback

proc `=destroy`*(obj: TabletSeatObj) =
  ## =====
  ## release the memory for the tablet seat object
  ## =====
  ## Destroy the zwp_tablet_seat_v2 object. Objects created from this object are unaffected and should be destroyed separately.
  zwp_tablet_seat_v2_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initTabletSeat*(raw: ptr zwp_tablet_seat_v2 | pointer): TabletSeat =
  ## Instantiate a TabletSeat using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTabletSeat() was given an uninitialized handle!")

  TabletSeat(handle: cast[ptr zwp_tablet_seat_v2](raw), payload: TabletSeatPayload())

func newTabletSeat*(raw: ptr zwp_tablet_seat_v2): TabletSeat =
  ## Instantiate a TabletSeat using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTabletSeat() was given an uninitialized handle!")

  TabletSeat(handle: raw, payload: TabletSeatPayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = zwp_tablet_seat_v2_listener(
  tablet_added: proc(
      data: pointer, this: ptr zwp_tablet_seat_v2, id: ptr zwp_tablet_v2
  ) {.cdecl.} =
    let payload = cast[TabletSeatPayload](data)
    if payload.tablet_addedCb == nil:
      write(stderr, "[nayland] handler not attached for event 'tablet_added'!\n")
      return

    payload.tablet_addedCb(initTablet(id)),
  tool_added: proc(
      data: pointer, this: ptr zwp_tablet_seat_v2, id: ptr zwp_tablet_tool_v2
  ) {.cdecl.} =
    let payload = cast[TabletSeatPayload](data)
    if payload.tool_addedCb == nil:
      write(stderr, "[nayland] handler not attached for event 'tool_added'!\n")
      return

    payload.tool_addedCb(initTabletTool(id)),
  pad_added: proc(
      data: pointer, this: ptr zwp_tablet_seat_v2, id: ptr zwp_tablet_pad_v2
  ) {.cdecl.} =
    let payload = cast[TabletSeatPayload](data)
    if payload.pad_addedCb == nil:
      write(stderr, "[nayland] handler not attached for event 'pad_added'!\n")
      return

    payload.pad_addedCb(initTabletPad(id)),
)
proc attachCallbacks*(obj: TabletSeat) =
  discard zwp_tablet_seat_v2_add_listener(
    obj.handle, listener.addr, cast[pointer](obj.payload)
  )

func `onTabletAdded=`*(
    obj: TabletSeat, cb: TabletSeatTabletAddedCallback
) {.inline, raises: [].} =
  obj.payload.tablet_addedCb = cb
func `onToolAdded=`*(
    obj: TabletSeat, cb: TabletSeatToolAddedCallback
) {.inline, raises: [].} =
  obj.payload.tool_addedCb = cb
func `onPadAdded=`*(
    obj: TabletSeat, cb: TabletSeatPadAddedCallback
) {.inline, raises: [].} =
  obj.payload.pad_addedCb = cb

# wrapgen: start emitting request wrappers

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
