## Wrapper around `zwp_tablet_pad_strip_v2` (`TabletPadStrip`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Source* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## strip axis source
    ## =====
    ## Describes the source types for strip events. This indicates to the client how a strip event was physically generated; a client may adjust the user interface accordingly. For example, events from a "finger" source may trigger kinetic scrolling.
    Finger = 1'u32 ## finger

  TabletPadStripObj* = object
    handle*: ptr zwp_tablet_pad_strip_v2
    payload: TabletPadStripPayload

  TabletPadStrip* = ref TabletPadStripObj
    ## =====
    ## pad strip
    ## =====
    ## A linear interaction area, such as the strips found in Wacom Cintiq models. Events on a strip are logically grouped by the zwp_tablet_pad_strip_v2.frame event.

  TabletPadStripSourceCallback* = proc(source: uint32)
  TabletPadStripPositionCallback* = proc(position: uint32)
  TabletPadStripStopCallback* = proc()
  TabletPadStripFrameCallback* = proc(time: uint32)
  TabletPadStripPayload = ref object
    sourceCb: TabletPadStripSourceCallback
    positionCb: TabletPadStripPositionCallback
    stopCb: TabletPadStripStopCallback
    frameCb: TabletPadStripFrameCallback


proc `=destroy`*(obj: TabletPadStripObj) =
  ## =====
  ## destroy the strip object
  ## =====
  ## This destroys the client's resource for this strip object.
  zwp_tablet_pad_strip_v2_destroy(obj.handle)


# wrapgen: begin emitting constructor routines
func initTabletPadStrip*(raw: ptr zwp_tablet_pad_strip_v2 | pointer): TabletPadStrip =
  ## Instantiate a TabletPadStrip using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTabletPadStrip() was given an uninitialized handle!")
  
  TabletPadStrip(handle: cast[ptr zwp_tablet_pad_strip_v2](raw), payload: TabletPadStripPayload())

func newTabletPadStrip*(raw: ptr zwp_tablet_pad_strip_v2): TabletPadStrip =
  ## Instantiate a TabletPadStrip using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTabletPadStrip() was given an uninitialized handle!")
  
  TabletPadStrip(handle: raw, payload: TabletPadStripPayload())

# wrapgen: end emitting constructor routines


let listener {.global.} =
  zwp_tablet_pad_strip_v2_listener(
    source: proc(data: pointer, this: ptr zwp_tablet_pad_strip_v2, source: uint32) {.cdecl.} =
      let payload = cast[TabletPadStripPayload](data)
      if payload.sourceCb == nil:
        write(stderr, "[nayland] handler not attached for event 'source'!\n")
        return

      payload.sourceCb(source)  ,    position: proc(data: pointer, this: ptr zwp_tablet_pad_strip_v2, position: uint32) {.cdecl.} =
      let payload = cast[TabletPadStripPayload](data)
      if payload.positionCb == nil:
        write(stderr, "[nayland] handler not attached for event 'position'!\n")
        return

      payload.positionCb(position)  ,    stop: proc(data: pointer, this: ptr zwp_tablet_pad_strip_v2) {.cdecl.} =
      let payload = cast[TabletPadStripPayload](data)
      if payload.stopCb == nil:
        write(stderr, "[nayland] handler not attached for event 'stop'!\n")
        return

      payload.stopCb()  ,    frame: proc(data: pointer, this: ptr zwp_tablet_pad_strip_v2, time: uint32) {.cdecl.} =
      let payload = cast[TabletPadStripPayload](data)
      if payload.frameCb == nil:
        write(stderr, "[nayland] handler not attached for event 'frame'!\n")
        return

      payload.frameCb(time)
)
proc attachCallbacks*(obj: TabletPadStrip) =
  discard zwp_tablet_pad_strip_v2_add_listener(obj.handle, listener.addr, cast[pointer](obj.payload))

func `onSource=`*(obj: TabletPadStrip, cb: TabletPadStripSourceCallback) {.inline, raises: [].} =
  obj.payload.sourceCb = cb
func `onPosition=`*(obj: TabletPadStrip, cb: TabletPadStripPositionCallback) {.inline, raises: [].} =
  obj.payload.positionCb = cb
func `onStop=`*(obj: TabletPadStrip, cb: TabletPadStripStopCallback) {.inline, raises: [].} =
  obj.payload.stopCb = cb
func `onFrame=`*(obj: TabletPadStrip, cb: TabletPadStripFrameCallback) {.inline, raises: [].} =
  obj.payload.frameCb = cb

# wrapgen: start emitting request wrappers

proc setFeedback*(obj: TabletPadStrip, Description: cstring, Serial: uint32) =
  ## =====
  ## set compositor feedback
  ## =====
  ## Requests the compositor to use the provided feedback string associated with this strip. This request should be issued immediately after a zwp_tablet_pad_group_v2.mode_switch event from the corresponding group is received, or whenever the strip is mapped to a different action. See zwp_tablet_pad_group_v2.mode_switch for more details. Clients are encouraged to provide context-aware descriptions for the actions associated with the strip, and compositors may use this information to offer visual feedback about the button layout (eg. on-screen displays). The provided string 'description' is a UTF-8 encoded string to be associated with this ring, and is considered user-visible; general internationalization rules apply. The serial argument will be that of the last zwp_tablet_pad_group_v2.mode_switch event received for the group of this strip. Requests providing other serials than the most recent one will be ignored.
  zwp_tablet_pad_strip_v2_set_feedback(obj.handle, Description, Serial)



# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Source): uint32 = cast[uint32](v)
# wrapgen: end emitting enum shims
