## Wrapper around `zwp_tablet_v2` (`Tablet`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Bustype* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## bus type
    ## =====
    ## Describes the bus types this tablet is connected to.
    Usb = 3'u32 ## USB
    Bluetooth = 5'u32 ## Bluetooth
    Virtual = 6'u32 ## Virtual
    Serial = 17'u32 ## Serial
    I2c = 24'u32 ## I2C

  TabletObj* = object
    handle*: ptr zwp_tablet_v2
    payload: TabletPayload

  Tablet* = ref TabletObj
    ## =====
    ## graphics tablet device
    ## =====
    ## The zwp_tablet_v2 interface represents one graphics tablet device. The tablet interface itself does not generate events; all events are generated by zwp_tablet_tool_v2 objects when in proximity above a tablet. A tablet has a number of static characteristics, e.g. device name and pid/vid. These capabilities are sent in an event sequence after the zwp_tablet_seat_v2.tablet_added event. This initial event sequence is terminated by a zwp_tablet_v2.done event.

  TabletNameCallback* = proc(name: cstring)
  TabletIdCallback* = proc(vid: uint32, pid: uint32)
  TabletPathCallback* = proc(path: cstring)
  TabletDoneCallback* = proc()
  TabletRemovedCallback* = proc()
  TabletBustypeCallback* = proc(bustype: uint32)
  TabletPayload = ref object
    nameCb: TabletNameCallback
    idCb: TabletIdCallback
    pathCb: TabletPathCallback
    doneCb: TabletDoneCallback
    removedCb: TabletRemovedCallback
    bustypeCb: TabletBustypeCallback


proc `=destroy`*(obj: TabletObj) =
  ## =====
  ## destroy the tablet object
  ## =====
  ## This destroys the client's resource for this tablet object.
  zwp_tablet_v2_destroy(obj.handle)


# wrapgen: begin emitting constructor routines
func initTablet*(raw: ptr zwp_tablet_v2 | pointer): Tablet =
  ## Instantiate a Tablet using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTablet() was given an uninitialized handle!")
  
  Tablet(handle: cast[ptr zwp_tablet_v2](raw), payload: TabletPayload())

func newTablet*(raw: ptr zwp_tablet_v2): Tablet =
  ## Instantiate a Tablet using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTablet() was given an uninitialized handle!")
  
  Tablet(handle: raw, payload: TabletPayload())

# wrapgen: end emitting constructor routines


let listener {.global.} =
  zwp_tablet_v2_listener(
    name: proc(data: pointer, this: ptr zwp_tablet_v2, name: cstring) {.cdecl.} =
      let payload = cast[TabletPayload](data)
      if payload.nameCb == nil:
        write(stderr, "[nayland] handler not attached for event 'name'!\n")
        return

      payload.nameCb(name)  ,    id: proc(data: pointer, this: ptr zwp_tablet_v2, vid: uint32, pid: uint32) {.cdecl.} =
      let payload = cast[TabletPayload](data)
      if payload.idCb == nil:
        write(stderr, "[nayland] handler not attached for event 'id'!\n")
        return

      payload.idCb(vid, pid)  ,    path: proc(data: pointer, this: ptr zwp_tablet_v2, path: cstring) {.cdecl.} =
      let payload = cast[TabletPayload](data)
      if payload.pathCb == nil:
        write(stderr, "[nayland] handler not attached for event 'path'!\n")
        return

      payload.pathCb(path)  ,    done: proc(data: pointer, this: ptr zwp_tablet_v2) {.cdecl.} =
      let payload = cast[TabletPayload](data)
      if payload.doneCb == nil:
        write(stderr, "[nayland] handler not attached for event 'done'!\n")
        return

      payload.doneCb()  ,    removed: proc(data: pointer, this: ptr zwp_tablet_v2) {.cdecl.} =
      let payload = cast[TabletPayload](data)
      if payload.removedCb == nil:
        write(stderr, "[nayland] handler not attached for event 'removed'!\n")
        return

      payload.removedCb()  ,    bustype: proc(data: pointer, this: ptr zwp_tablet_v2, bustype: uint32) {.cdecl.} =
      let payload = cast[TabletPayload](data)
      if payload.bustypeCb == nil:
        write(stderr, "[nayland] handler not attached for event 'bustype'!\n")
        return

      payload.bustypeCb(bustype)
)
proc attachCallbacks*(obj: Tablet) =
  discard zwp_tablet_v2_add_listener(obj.handle, listener.addr, cast[pointer](obj.payload))

func `onName=`*(obj: Tablet, cb: TabletNameCallback) {.inline, raises: [].} =
  obj.payload.nameCb = cb
func `onId=`*(obj: Tablet, cb: TabletIdCallback) {.inline, raises: [].} =
  obj.payload.idCb = cb
func `onPath=`*(obj: Tablet, cb: TabletPathCallback) {.inline, raises: [].} =
  obj.payload.pathCb = cb
func `onDone=`*(obj: Tablet, cb: TabletDoneCallback) {.inline, raises: [].} =
  obj.payload.doneCb = cb
func `onRemoved=`*(obj: Tablet, cb: TabletRemovedCallback) {.inline, raises: [].} =
  obj.payload.removedCb = cb
func `onBustype=`*(obj: Tablet, cb: TabletBustypeCallback) {.inline, raises: [].} =
  obj.payload.bustypeCb = cb

# wrapgen: start emitting request wrappers


# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Bustype): uint32 = cast[uint32](v)
# wrapgen: end emitting enum shims
