## Wrapper around `zwp_tablet_v2` (`Tablet`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Bustype* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## bus type
    ## =====
    ## Describes the bus types this tablet is connected to.
    Usb = 3'u32 ## USB
    Bluetooth = 5'u32 ## Bluetooth
    Virtual = 6'u32 ## Virtual
    Serial = 17'u32 ## Serial
    I2c = 24'u32 ## I2C

  TabletObj* = object
    handle*: ptr zwp_tablet_v2

  Tablet* = ref TabletObj
    ## =====
    ## tablet device bus type
    ## =====
    ## The bustype argument is one of the BUS_ defines in the Linux kernel's linux/input.h If the device has no known bustype or the bustype cannot be queried, this event is not sent. This event is sent in the initial burst of events before the zwp_tablet_v2.done event.

# wrapgen: end emitting interface structures
# wrapgen: start emitting request wrappers
proc `=destroy`*(obj: TabletObj) =
  ## =====
  ## destroy the tablet object
  ## =====
  ## This destroys the client's resource for this tablet object.
  zwp_tablet_v2_destroy(obj.handle)



# wrapgen: end emitting request wrappers
# wrapgen: begin emitting constructor routines
func initTablet*(raw: ptr zwp_tablet_v2 | pointer): Tablet =
  ## Instantiate a Tablet using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTablet() was given an uninitialized handle!")
  
  Tablet(handle: cast[ptr zwp_tablet_v2](raw))

func newTablet*(raw: ptr zwp_tablet_v2): Tablet =
  ## Instantiate a Tablet using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTablet() was given an uninitialized handle!")
  
  Tablet(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting enum shims
converter shim0*(v: Bustype): uint32 = cast[uint32](v)
# wrapgen: end emitting enum shims
