## Wrapper around `zwp_tablet_tool_v2` (`TabletTool`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tablet_v2]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Type* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## a physical tool type
    ## =====
    ## Describes the physical type of a tool. The physical type of a tool generally defines its base usage. The mouse tool represents a mouse-shaped tool that is not a relative device but bound to the tablet's surface, providing absolute coordinates. The lens tool is a mouse-shaped tool with an attached lens to provide precision focus.
    Pen = 320'u32 ## Pen
    Eraser = 321'u32 ## Eraser
    Brush = 322'u32 ## Brush
    Pencil = 323'u32 ## Pencil
    Airbrush = 324'u32 ## Airbrush
    Finger = 325'u32 ## Finger
    Mouse = 326'u32 ## Mouse
    Lens = 327'u32 ## Lens

  Capability* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## capability flags for a tool
    ## =====
    ## Describes extra capabilities on a tablet. Any tool must provide x and y values, extra axes are device-specific.
    Tilt = 1'u32 ## Tilt axes
    Pressure = 2'u32 ## Pressure axis
    Distance = 3'u32 ## Distance axis
    Rotation = 4'u32 ## Z-rotation axis
    Slider = 5'u32 ## Slider axis
    Wheel = 6'u32 ## Wheel axis

  Button_state* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## physical button state
    ## =====
    ## Describes the physical state of a button that produced the button event.
    Released = 0'u32 ## button is not pressed
    Pressed = 1'u32 ## button is pressed

  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    Role = 0'u32 ## given wl_surface has another role

  TabletToolObj* = object
    handle*: ptr zwp_tablet_tool_v2

  TabletTool* = ref TabletToolObj
    ## =====
    ## frame event
    ## =====
    ## Marks the end of a series of axis and/or button updates from the tablet. The Wayland protocol requires axis updates to be sent sequentially, however all events within a frame should be considered one hardware event.

# wrapgen: end emitting interface structures
# wrapgen: start emitting request wrappers

proc setCursor*(obj: TabletTool, Serial: uint32, Surface: Surface, HotspotX: int, HotspotY: int) =
  ## =====
  ## set the tablet tool's surface
  ## =====
  ## Sets the surface of the cursor used for this tool on the given tablet. This request only takes effect if the tool is in proximity of one of the requesting client's surfaces or the surface parameter is the current pointer surface. If there was a previous surface set with this request it is replaced. If surface is NULL, the cursor image is hidden. The parameters hotspot_x and hotspot_y define the position of the pointer surface relative to the pointer location. Its top-left corner is always at (x, y) - (hotspot_x, hotspot_y), where (x, y) are the coordinates of the pointer location, in surface-local coordinates. On surface.attach requests to the pointer surface, hotspot_x and hotspot_y are decremented by the x and y parameters passed to the request. Attach must be confirmed by wl_surface.commit as usual. The hotspot can also be updated by passing the currently set pointer surface to this request with new values for hotspot_x and hotspot_y. The current and pending input regions of the wl_surface are cleared, and wl_surface.set_input_region is ignored until the wl_surface is no longer used as the cursor. When the use as a cursor ends, the current and pending input regions become undefined, and the wl_surface is unmapped. This request gives the surface the role of a zwp_tablet_tool_v2 cursor. A surface may only ever be used as the cursor surface for one zwp_tablet_tool_v2. If the surface already has another role or has previously been used as cursor surface for a different tool, a protocol error is raised.
  zwp_tablet_tool_v2_set_cursor(obj.handle, Serial, Surface.handle, HotspotX.handle, HotspotY.handle)

proc `=destroy`*(obj: TabletToolObj) =
  ## =====
  ## destroy the tool object
  ## =====
  ## This destroys the client's resource for this tool object.
  zwp_tablet_tool_v2_destroy(obj.handle)



# wrapgen: end emitting request wrappers
# wrapgen: begin emitting constructor routines
func initTabletTool*(raw: ptr zwp_tablet_tool_v2 | pointer): TabletTool =
  ## Instantiate a TabletTool using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTabletTool() was given an uninitialized handle!")
  
  TabletTool(handle: cast[ptr zwp_tablet_tool_v2](raw))

func newTabletTool*(raw: ptr zwp_tablet_tool_v2): TabletTool =
  ## Instantiate a TabletTool using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTabletTool() was given an uninitialized handle!")
  
  TabletTool(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting enum shims
converter shim0*(v: Type): uint32 = cast[uint32](v)
converter shim1*(v: Capability): uint32 = cast[uint32](v)
converter shim2*(v: Button_state): uint32 = cast[uint32](v)
converter shim3*(v: Error): uint32 = cast[uint32](v)
# wrapgen: end emitting enum shims
