## Wrapper around `wp_tearing_control_v1` (`TearingControl`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tearing_control_v1]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Presentation_hint* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## asynchronous presentation
    ## =====
    ## The content of this surface is meant to be presented with minimal latency and tearing is acceptable.
    Vsync = 0'u32 ## 
    Async = 1'u32 ## 

  TearingControlObj* = object
    handle*: ptr wp_tearing_control_v1

  TearingControl* = ref TearingControlObj
    ## =====
    ## per-surface tearing control interface
    ## =====
    ## An additional interface to a wl_surface object, which allows the client to hint to the compositor if the content on the surface is suitable for presentation with tearing. The default presentation hint is vsync. See presentation_hint for more details. If the associated wl_surface is destroyed, this object becomes inert and should be destroyed.

proc `=destroy`*(obj: TearingControlObj) =
  ## =====
  ## destroy tearing control object
  ## =====
  ## Destroy this surface tearing object and revert the presentation hint to vsync. The change will be applied on the next wl_surface.commit.
  wp_tearing_control_v1_destroy(obj.handle)


# wrapgen: begin emitting constructor routines
func initTearingControl*(raw: ptr wp_tearing_control_v1 | pointer): TearingControl =
  ## Instantiate a TearingControl using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initTearingControl() was given an uninitialized handle!")
  
  TearingControl(handle: cast[ptr wp_tearing_control_v1](raw))

func newTearingControl*(raw: ptr wp_tearing_control_v1): TearingControl =
  ## Instantiate a TearingControl using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newTearingControl() was given an uninitialized handle!")
  
  TearingControl(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc setPresentationHint*(obj: TearingControl, Hint: uint32) =
  ## =====
  ## set presentation hint
  ## =====
  ## Set the presentation hint for the associated wl_surface. This state is double-buffered, see wl_surface.commit. The compositor is free to dynamically respect or ignore this hint based on various conditions like hardware capabilities, surface state and user preferences.
  wp_tearing_control_v1_set_presentation_hint(obj.handle, Hint)



# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Presentation_hint): uint32 = cast[uint32](v)
# wrapgen: end emitting enum shims
