## Wrapper around `wp_tearing_control_manager_v1` (`TearingControlManager`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, tearing_control_v1]
import pkg/nayland/types/protocols/core/prelude
import pkg/nayland/types/protocols/tearing_control/control
# wrapgen: begin emitting interface structures
type
  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    TearingControlExists = 0'u32 ## the surface already has a tearing object associated

  TearingControlManagerObj* = object
    handle*: ptr wp_tearing_control_manager_v1

  TearingControlManager* = ref TearingControlManagerObj
    ## =====
    ## protocol for tearing control
    ## =====
    ## For some use cases like games or drawing tablets it can make sense to reduce latency by accepting tearing with the use of asynchronous page flips. This global is a factory interface, allowing clients to inform which type of presentation the content of their surfaces is suitable for. Graphics APIs like EGL or Vulkan, that manage the buffer queue and commits of a wl_surface themselves, are likely to be using this extension internally. If a client is using such an API for a wl_surface, it should not directly use this extension on that surface, to avoid raising a tearing_control_exists protocol error. Warning! The protocol described in this file is currently in the testing phase. Backward compatible changes may be added together with the corresponding interface version bump. Backward incompatible changes can only be done by creating a new major version of the extension.

proc `=destroy`*(obj: TearingControlManagerObj) =
  ## =====
  ## destroy tearing control factory object
  ## =====
  ## Destroy this tearing control factory object. Other objects, including wp_tearing_control_v1 objects created by this factory, are not affected by this request.
  wp_tearing_control_manager_v1_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initTearingControlManager*(
    raw: ptr wp_tearing_control_manager_v1 | pointer
): TearingControlManager =
  ## Instantiate a TearingControlManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initTearingControlManager() was given an uninitialized handle!"
    )

  TearingControlManager(handle: cast[ptr wp_tearing_control_manager_v1](raw))

func newTearingControlManager*(
    raw: ptr wp_tearing_control_manager_v1
): TearingControlManager =
  ## Instantiate a TearingControlManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: newTearingControlManager() was given an uninitialized handle!"
    )

  TearingControlManager(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc getTearingControl*(obj: TearingControlManager, Surface: Surface): TearingControl =
  ## =====
  ## extend surface interface for tearing control
  ## =====
  ## Instantiate an interface extension for the given wl_surface to request asynchronous page flips for presentation. If the given wl_surface already has a wp_tearing_control_v1 object associated, the tearing_control_exists protocol error is raised.
  initTearingControl(
    wp_tearing_control_manager_v1_get_tearing_control(obj.handle, Surface.handle)
  )

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Error): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
