## Wrapper around `org_kde_kwin_blur` (`org_kwinBlur`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, kde_blur]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  KWinBlurObj* = object
    handle*: ptr org_kde_kwin_blur

  KWinBlur* = ref KWinBlurObj
    ## =====
    ## 
    ## =====
    ## 

proc `=destroy`*(obj: KWinBlurObj) =
  ## =====
  ## release the blur object
  ## =====
  ## 
  org_kde_kwin_blur_release(obj.handle)

# wrapgen: begin emitting constructor routines
func initKWinBlur*(raw: ptr org_kde_kwin_blur | pointer): KWinBlur =
  ## Instantiate a org_kwinBlur using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initorg_kwinBlur() was given an uninitialized handle!")

  KWinBlur(handle: cast[ptr org_kde_kwin_blur](raw))

func newKWinBlur*(raw: ptr org_kde_kwin_blur): KWinBlur =
  ## Instantiate a org_kwinBlur using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: neworg_kwinBlur() was given an uninitialized handle!")

  KWinBlur(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc commit*(obj: KWinBlur) =
  ## =====
  ## 
  ## =====
  ## 
  org_kde_kwin_blur_commit(obj.handle)

proc setRegion*(obj: KWinBlur, Region: Region) =
  ## =====
  ## 
  ## =====
  ## 
  org_kde_kwin_blur_set_region(obj.handle, Region.handle)

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
