## Wrapper around `org_kde_kwin_blur_manager` (`org_kwinBlurManager`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, kde_blur]
import pkg/nayland/types/protocols/core/prelude
import pkg/nayland/types/protocols/kde_blur/blur
# wrapgen: begin emitting interface structures
type
  KWinBlurManagerObj* = object
    handle*: ptr org_kde_kwin_blur_manager

  KWinBlurManager* = ref KWinBlurManagerObj
    ## =====
    ## 
    ## =====
    ## 

# wrapgen: begin emitting constructor routines
func initKWinBlurManager*(
    raw: ptr org_kde_kwin_blur_manager | pointer
): KWinBlurManager =
  ## Instantiate a org_kwinBlurManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initorg_kwinBlurManager() was given an uninitialized handle!"
    )

  KWinBlurManager(handle: cast[ptr org_kde_kwin_blur_manager](raw))

func newKWinBlurManager*(raw: ptr org_kde_kwin_blur_manager): KWinBlurManager =
  ## Instantiate a org_kwinBlurManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: neworg_kwinBlurManager() was given an uninitialized handle!"
    )

  KWinBlurManager(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc create*(obj: KWinBlurManager, Surface: Surface): KWinBlur =
  ## =====
  ## 
  ## =====
  ## 
  initKWinBlur(org_kde_kwin_blur_manager_create(obj.handle, Surface.handle))

proc unset*(obj: KWinBlurManager, Surface: Surface) =
  ## =====
  ## 
  ## =====
  ## 
  org_kde_kwin_blur_manager_unset(obj.handle, Surface.handle)

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
