## Wrapper around `ext_session_lock_manager_v1` (`SessionLockManager`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, ext_session_lock_v1]
import
  pkg/nayland/types/protocols/core/prelude,
  pkg/nayland/types/protocols/ext_session_lock/[lock, surface]
# wrapgen: begin emitting interface structures
type
  SessionLockManagerObj* = object
    handle*: ptr ext_session_lock_manager_v1

  SessionLockManager* = ref SessionLockManagerObj
    ## =====
    ## used to lock the session
    ## =====
    ## This interface is used to request that the session be locked.

proc `=destroy`*(obj: SessionLockManagerObj) =
  ## =====
  ## destroy the session lock manager object
  ## =====
  ## This informs the compositor that the session lock manager object will no longer be used. Existing objects created through this interface remain valid.
  ext_session_lock_manager_v1_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initSessionLockManager*(
    raw: ptr ext_session_lock_manager_v1 | pointer
): SessionLockManager =
  ## Instantiate a SessionLockManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initSessionLockManager() was given an uninitialized handle!"
    )

  SessionLockManager(handle: cast[ptr ext_session_lock_manager_v1](raw))

func newSessionLockManager*(raw: ptr ext_session_lock_manager_v1): SessionLockManager =
  ## Instantiate a SessionLockManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: newSessionLockManager() was given an uninitialized handle!"
    )

  SessionLockManager(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc lock*(obj: SessionLockManager): SessionLock =
  ## =====
  ## attempt to lock the session
  ## =====
  ## This request creates a session lock and asks the compositor to lock the session. The compositor will send either the ext_session_lock_v1.locked or ext_session_lock_v1.finished event on the created object in response to this request.
  initSessionLock(ext_session_lock_manager_v1_lock(obj.handle))

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
