## Wrapper around `ext_session_lock_surface_v1` (`SessionLockSurface`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, ext_session_lock_v1]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    CommitBeforeFirstAck = 0'u32 ## surface committed before first ack_configure request
    NullBuffer = 1'u32 ## surface committed with a null buffer
    DimensionsMismatch = 2'u32 ## failed to match ack'd width/height
    InvalidSerial = 3'u32 ## serial provided in ack_configure is invalid

  SessionLockSurfaceObj* = object
    handle*: ptr ext_session_lock_surface_v1
    payload: SessionLockSurfacePayload

  SessionLockSurface* = ref SessionLockSurfaceObj
    ## =====
    ## a surface displayed while the session is locked
    ## =====
    ## The client may use lock surfaces to display a screensaver, render a dialog to enter a password and unlock the session, or however else it sees fit. On binding this interface the compositor will immediately send the first configure event. After making the ack_configure request in response to this event the client should attach and commit the first buffer. Committing the surface before acking the first configure is a protocol error. Committing the surface with a null buffer at any time is a protocol error. The compositor is free to handle keyboard/pointer focus for lock surfaces however it chooses. A reasonable way to do this would be to give the first lock surface created keyboard focus and change keyboard focus if the user clicks on other surfaces.

  SessionLockSurfaceConfigureCallback* =
    proc(serial: uint32, width: uint32, height: uint32)
  SessionLockSurfacePayload = ref object
    configureCb: SessionLockSurfaceConfigureCallback

proc `=destroy`*(obj: SessionLockSurfaceObj) =
  ## =====
  ## destroy the lock surface object
  ## =====
  ## This informs the compositor that the lock surface object will no longer be used. It is recommended for a lock client to destroy lock surfaces if their corresponding wl_output global is removed. If a lock surface on an active output is destroyed before the ext_session_lock_v1.unlock_and_destroy event is sent, the compositor must fall back to rendering a solid color.
  ext_session_lock_surface_v1_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initSessionLockSurface*(
    raw: ptr ext_session_lock_surface_v1 | pointer
): SessionLockSurface =
  ## Instantiate a SessionLockSurface using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initSessionLockSurface() was given an uninitialized handle!"
    )

  SessionLockSurface(
    handle: cast[ptr ext_session_lock_surface_v1](raw),
    payload: SessionLockSurfacePayload(),
  )

func newSessionLockSurface*(raw: ptr ext_session_lock_surface_v1): SessionLockSurface =
  ## Instantiate a SessionLockSurface using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: newSessionLockSurface() was given an uninitialized handle!"
    )

  SessionLockSurface(handle: raw, payload: SessionLockSurfacePayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = ext_session_lock_surface_v1_listener(
  configure: proc(
      data: pointer,
      this: ptr ext_session_lock_surface_v1,
      serial: uint32,
      width: uint32,
      height: uint32,
  ) {.cdecl.} =
    let payload = cast[SessionLockSurfacePayload](data)
    if payload.configureCb == nil:
      write(stderr, "[nayland] handler not attached for event 'configure'!\n")
      return

    payload.configureCb(serial, width, height)
)
proc attachCallbacks*(obj: SessionLockSurface) =
  discard ext_session_lock_surface_v1_add_listener(
    obj.handle, listener.addr, cast[pointer](obj.payload)
  )

func `onConfigure=`*(
    obj: SessionLockSurface, cb: SessionLockSurfaceConfigureCallback
) {.inline, raises: [].} =
  obj.payload.configureCb = cb

# wrapgen: start emitting request wrappers

proc ackConfigure*(obj: SessionLockSurface, Serial: uint32) =
  ## =====
  ## ack a configure event
  ## =====
  ## When a configure event is received, if a client commits the surface in response to the configure event, then the client must make an ack_configure request sometime before the commit request, passing along the serial of the configure event. If the client receives multiple configure events before it can respond to one, it only has to ack the last configure event. A client is not required to commit immediately after sending an ack_configure request - it may even ack_configure several times before its next surface commit. A client may send multiple ack_configure requests before committing, but only the last request sent before a commit indicates which configure event the client really is responding to. Sending an ack_configure request consumes the configure event referenced by the given serial, as well as all older configure events sent on this object. It is a protocol error to issue multiple ack_configure requests referencing the same configure event or to issue an ack_configure request referencing a configure event older than the last configure event acked for a given lock surface.
  ext_session_lock_surface_v1_ack_configure(obj.handle, Serial)

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Error): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
