## Generated by nayland-bindgen. Do not edit!
import pkg/nayland/bindings/protocols/core

# Link private code for protocol
{.compile("private-code/ext_idle_notify_v1.c", core.LibwaylandCflags).}

##  Generated by wayland-scanner 1.25.0

import pkg/nayland/bindings/libwayland

##
##  @page page_ext_idle_notify_v1 The ext_idle_notify_v1 protocol
##  @section page_ifaces_ext_idle_notify_v1 Interfaces
##  - @subpage page_iface_ext_idle_notifier_v1 - idle notification manager
##  - @subpage page_iface_ext_idle_notification_v1 - idle notification
##  @section page_copyright_ext_idle_notify_v1 Copyright
##  <pre>
##
##  Copyright © 2015 Martin Gräßlin
##  Copyright © 2022 Simon Ser
##
##  Permission is hereby granted, free of charge, to any person obtaining a
##  copy of this software and associated documentation files (the "Software"),
##  to deal in the Software without restriction, including without limitation
##  the rights to use, copy, modify, merge, publish, distribute, sublicense,
##  and/or sell copies of the Software, and to permit persons to whom the
##  Software is furnished to do so, subject to the following conditions:
##
##  The above copyright notice and this permission notice (including the next
##  paragraph) shall be included in all copies or substantial portions of the
##  Software.
##
##  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
##  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
##  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
##  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
##  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
##  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
##  DEALINGS IN THE SOFTWARE.
##  </pre>
##

type ext_idle_notification_v1* = object
type ext_idle_notifier_v1* = object
discard "forward decl of wl_seat"
##
##  @page page_iface_ext_idle_notifier_v1 ext_idle_notifier_v1
##  @section page_iface_ext_idle_notifier_v1_desc Description
##
##  This interface allows clients to monitor user idle status.
##
##  After binding to this global, clients can create ext_idle_notification_v1
##  objects to get notified when the user is idle for a given amount of time.
##  @section page_iface_ext_idle_notifier_v1_api API
##  See @ref iface_ext_idle_notifier_v1.
##
##
##  @defgroup iface_ext_idle_notifier_v1 The ext_idle_notifier_v1 interface
##
##  This interface allows clients to monitor user idle status.
##
##  After binding to this global, clients can create ext_idle_notification_v1
##  objects to get notified when the user is idle for a given amount of time.
##

let ext_idle_notifier_v1_interface* {.importc.}: wl_interface

##
##  @page page_iface_ext_idle_notification_v1 ext_idle_notification_v1
##  @section page_iface_ext_idle_notification_v1_desc Description
##
##  This interface is used by the compositor to send idle notification events
##  to clients.
##
##  Initially the notification object is not idle. The notification object
##  becomes idle when no user activity has happened for at least the timeout
##  duration, starting from the creation of the notification object. User
##  activity may include input events or a presence sensor, but is
##  compositor-specific.
##
##  How this notification responds to idle inhibitors depends on how
##  it was constructed. If constructed from the
##  get_idle_notification request, then if an idle inhibitor is
##  active (e.g. another client has created a zwp_idle_inhibitor_v1
##  on a visible surface), the compositor must not make the
##  notification object idle. However, if constructed from the
##  get_input_idle_notification request, then idle inhibitors are
##  ignored, and only input from the user, e.g. from a keyboard or
##  mouse, counts as activity.
##
##  When the notification object becomes idle, an idled event is sent. When
##  user activity starts again, the notification object stops being idle,
##  a resumed event is sent and the timeout is restarted.
##  @section page_iface_ext_idle_notification_v1_api API
##  See @ref iface_ext_idle_notification_v1.
##
##
##  @defgroup iface_ext_idle_notification_v1 The ext_idle_notification_v1 interface
##
##  This interface is used by the compositor to send idle notification events
##  to clients.
##
##  Initially the notification object is not idle. The notification object
##  becomes idle when no user activity has happened for at least the timeout
##  duration, starting from the creation of the notification object. User
##  activity may include input events or a presence sensor, but is
##  compositor-specific.
##
##  How this notification responds to idle inhibitors depends on how
##  it was constructed. If constructed from the
##  get_idle_notification request, then if an idle inhibitor is
##  active (e.g. another client has created a zwp_idle_inhibitor_v1
##  on a visible surface), the compositor must not make the
##  notification object idle. However, if constructed from the
##  get_input_idle_notification request, then idle inhibitors are
##  ignored, and only input from the user, e.g. from a keyboard or
##  mouse, counts as activity.
##
##  When the notification object becomes idle, an idled event is sent. When
##  user activity starts again, the notification object stops being idle,
##  a resumed event is sent and the timeout is restarted.
##

let ext_idle_notification_v1_interface* {.importc.}: wl_interface

const
  EXT_IDLE_NOTIFIER_V1_DESTROY* = 0
  EXT_IDLE_NOTIFIER_V1_GET_IDLE_NOTIFICATION* = 1
  EXT_IDLE_NOTIFIER_V1_GET_INPUT_IDLE_NOTIFICATION* = 2

##
##  @ingroup iface_ext_idle_notifier_v1
##

const EXT_IDLE_NOTIFIER_V1_DESTROY_SINCE_VERSION* = 1

##
##  @ingroup iface_ext_idle_notifier_v1
##

const EXT_IDLE_NOTIFIER_V1_GET_IDLE_NOTIFICATION_SINCE_VERSION* = 1

##
##  @ingroup iface_ext_idle_notifier_v1
##

const EXT_IDLE_NOTIFIER_V1_GET_INPUT_IDLE_NOTIFICATION_SINCE_VERSION* = 2

##  @ingroup iface_ext_idle_notifier_v1

proc ext_idle_notifier_v1_set_user_data*(
    ext_idle_notifier_v1: ptr ext_idle_notifier_v1, user_data: pointer
) {.inline, cdecl.} =
  wl_proxy_set_user_data(cast[ptr wl_proxy](ext_idle_notifier_v1), user_data)

##  @ingroup iface_ext_idle_notifier_v1

proc ext_idle_notifier_v1_get_user_data*(
    ext_idle_notifier_v1: ptr ext_idle_notifier_v1
): pointer {.inline, cdecl.} =
  return wl_proxy_get_user_data(cast[ptr wl_proxy](ext_idle_notifier_v1))

proc ext_idle_notifier_v1_get_version*(
    ext_idle_notifier_v1: ptr ext_idle_notifier_v1
): uint32 {.inline, cdecl.} =
  return wl_proxy_get_version(cast[ptr wl_proxy](ext_idle_notifier_v1))

##
##  @ingroup iface_ext_idle_notifier_v1
##
##  Destroy the manager object. All objects created via this interface
##  remain valid.
##

proc ext_idle_notifier_v1_destroy*(
    ext_idle_notifier_v1: ptr ext_idle_notifier_v1
) {.inline, cdecl.} =
  wl_proxy_marshal_flags(
    cast[ptr wl_proxy](ext_idle_notifier_v1),
    EXT_IDLE_NOTIFIER_V1_DESTROY,
    nil,
    wl_proxy_get_version(cast[ptr wl_proxy](ext_idle_notifier_v1)),
    WL_MARSHAL_FLAG_DESTROY,
  )

##
##  @ingroup iface_ext_idle_notifier_v1
##
##  Create a new idle notification object.
##
##  The notification object has a minimum timeout duration and is tied to a
##  seat. The client will be notified if the seat is inactive for at least
##  the provided timeout. See ext_idle_notification_v1 for more details.
##
##  A zero timeout is valid and means the client wants to be notified as
##  soon as possible when the seat is inactive.
##

proc ext_idle_notifier_v1_get_idle_notification*(
    ext_idle_notifier_v1: ptr ext_idle_notifier_v1, timeout: uint32, seat: ptr wl_seat
): ptr ext_idle_notification_v1 {.inline, cdecl.} =
  var id: ptr wl_proxy
  id = wl_proxy_marshal_flags(
    cast[ptr wl_proxy](ext_idle_notifier_v1),
    EXT_IDLE_NOTIFIER_V1_GET_IDLE_NOTIFICATION,
    addr(ext_idle_notification_v1_interface),
    wl_proxy_get_version(cast[ptr wl_proxy](ext_idle_notifier_v1)),
    0,
    nil,
    timeout,
    seat,
  )
  return cast[ptr ext_idle_notification_v1](id)

##
##  @ingroup iface_ext_idle_notifier_v1
##
##  Create a new idle notification object to track input from the
##  user, such as keyboard and mouse movement. Because this object is
##  meant to track user input alone, it ignores idle inhibitors.
##
##  The notification object has a minimum timeout duration and is tied to a
##  seat. The client will be notified if the seat is inactive for at least
##  the provided timeout. See ext_idle_notification_v1 for more details.
##
##  A zero timeout is valid and means the client wants to be notified as
##  soon as possible when the seat is inactive.
##

proc ext_idle_notifier_v1_get_input_idle_notification*(
    ext_idle_notifier_v1: ptr ext_idle_notifier_v1, timeout: uint32, seat: ptr wl_seat
): ptr ext_idle_notification_v1 {.inline, cdecl.} =
  var id: ptr wl_proxy
  id = wl_proxy_marshal_flags(
    cast[ptr wl_proxy](ext_idle_notifier_v1),
    EXT_IDLE_NOTIFIER_V1_GET_INPUT_IDLE_NOTIFICATION,
    addr(ext_idle_notification_v1_interface),
    wl_proxy_get_version(cast[ptr wl_proxy](ext_idle_notifier_v1)),
    0,
    nil,
    timeout,
    seat,
  )
  return cast[ptr ext_idle_notification_v1](id)

##
##  @ingroup iface_ext_idle_notification_v1
##  @struct ext_idle_notification_v1_listener
##

type ext_idle_notification_v1_listener* {.bycopy.} = object
  ##
  ##  notification object is idle
  ##
  ##  This event is sent when the notification object becomes idle.
  ##
  ##  It's a compositor protocol error to send this event twice
  ##  without a resumed event in-between.
  ##
  idled*: proc(data: pointer, ext_idle_notification_v1: ptr ext_idle_notification_v1) {.
    cdecl
  .}
  ##
  ##  notification object is no longer idle
  ##
  ##  This event is sent when the notification object stops being
  ##  idle.
  ##
  ##  It's a compositor protocol error to send this event twice
  ##  without an idled event in-between. It's a compositor protocol
  ##  error to send this event prior to any idled event.
  ##
  resumed*: proc(data: pointer, ext_idle_notification_v1: ptr ext_idle_notification_v1) {.
    cdecl
  .}

##
##  @ingroup iface_ext_idle_notification_v1
##

proc ext_idle_notification_v1_add_listener*(
    ext_idle_notification_v1: ptr ext_idle_notification_v1,
    listener: ptr ext_idle_notification_v1_listener,
    data: pointer,
): cint {.inline, cdecl.} =
  return wl_proxy_add_listener(
    cast[ptr wl_proxy](ext_idle_notification_v1),
    cast[ptr proc() {.cdecl.}](listener),
    data,
  )

const EXT_IDLE_NOTIFICATION_V1_DESTROY* = 0

##
##  @ingroup iface_ext_idle_notification_v1
##

const EXT_IDLE_NOTIFICATION_V1_IDLED_SINCE_VERSION* = 1

##
##  @ingroup iface_ext_idle_notification_v1
##

const EXT_IDLE_NOTIFICATION_V1_RESUMED_SINCE_VERSION* = 1

##
##  @ingroup iface_ext_idle_notification_v1
##

const EXT_IDLE_NOTIFICATION_V1_DESTROY_SINCE_VERSION* = 1

##  @ingroup iface_ext_idle_notification_v1

proc ext_idle_notification_v1_set_user_data*(
    ext_idle_notification_v1: ptr ext_idle_notification_v1, user_data: pointer
) {.inline, cdecl.} =
  wl_proxy_set_user_data(cast[ptr wl_proxy](ext_idle_notification_v1), user_data)

##  @ingroup iface_ext_idle_notification_v1

proc ext_idle_notification_v1_get_user_data*(
    ext_idle_notification_v1: ptr ext_idle_notification_v1
): pointer {.inline, cdecl.} =
  return wl_proxy_get_user_data(cast[ptr wl_proxy](ext_idle_notification_v1))

proc ext_idle_notification_v1_get_version*(
    ext_idle_notification_v1: ptr ext_idle_notification_v1
): uint32 {.inline, cdecl.} =
  return wl_proxy_get_version(cast[ptr wl_proxy](ext_idle_notification_v1))

##
##  @ingroup iface_ext_idle_notification_v1
##
##  Destroy the notification object.
##

proc ext_idle_notification_v1_destroy*(
    ext_idle_notification_v1: ptr ext_idle_notification_v1
) {.inline, cdecl.} =
  wl_proxy_marshal_flags(
    cast[ptr wl_proxy](ext_idle_notification_v1),
    EXT_IDLE_NOTIFICATION_V1_DESTROY,
    nil,
    wl_proxy_get_version(cast[ptr wl_proxy](ext_idle_notification_v1)),
    WL_MARSHAL_FLAG_DESTROY,
  )
