## Generated by nayland-bindgen. Do not edit!
import pkg/nayland/bindings/protocols/core

# Link private code for protocol
{.compile("private-code/kde_blur.c", core.LibwaylandCflags).}

##  Generated by wayland-scanner 1.24.0

import pkg/nayland/bindings/libwayland

##
##  @page page_blur The blur protocol
##  @section page_ifaces_blur Interfaces
##  - @subpage page_iface_org_kde_kwin_blur_manager -
##  - @subpage page_iface_org_kde_kwin_blur -
##  @section page_copyright_blur Copyright
##  <pre>
##
##  SPDX-FileCopyrightText: 2015 Martin Gräßlin
##  SPDX-FileCopyrightText: 2015 Marco Martin
##
##  SPDX-License-Identifier: LGPL-2.1-or-later
##  </pre>
##

type org_kde_kwin_blur* = object
type org_kde_kwin_blur_manager* = object
discard "forward decl of wl_region"
discard "forward decl of wl_surface"
##
##  @page page_iface_org_kde_kwin_blur_manager org_kde_kwin_blur_manager
##  @section page_iface_org_kde_kwin_blur_manager_api API
##  See @ref iface_org_kde_kwin_blur_manager.
##
##
##  @defgroup iface_org_kde_kwin_blur_manager The org_kde_kwin_blur_manager interface
##

let org_kde_kwin_blur_manager_interface* {.importc.}: wl_interface

##
##  @page page_iface_org_kde_kwin_blur org_kde_kwin_blur
##  @section page_iface_org_kde_kwin_blur_api API
##  See @ref iface_org_kde_kwin_blur.
##
##
##  @defgroup iface_org_kde_kwin_blur The org_kde_kwin_blur interface
##

let org_kde_kwin_blur_interface* {.importc.}: wl_interface

const
  ORG_KDE_KWIN_BLUR_MANAGER_CREATE* = 0
  ORG_KDE_KWIN_BLUR_MANAGER_UNSET* = 1

##
##  @ingroup iface_org_kde_kwin_blur_manager
##

const ORG_KDE_KWIN_BLUR_MANAGER_CREATE_SINCE_VERSION* = 1

##
##  @ingroup iface_org_kde_kwin_blur_manager
##

const ORG_KDE_KWIN_BLUR_MANAGER_UNSET_SINCE_VERSION* = 1

##  @ingroup iface_org_kde_kwin_blur_manager

proc org_kde_kwin_blur_manager_set_user_data*(
    org_kde_kwin_blur_manager: ptr org_kde_kwin_blur_manager, user_data: pointer
) {.inline, cdecl.} =
  wl_proxy_set_user_data(cast[ptr wl_proxy](org_kde_kwin_blur_manager), user_data)

##  @ingroup iface_org_kde_kwin_blur_manager

proc org_kde_kwin_blur_manager_get_user_data*(
    org_kde_kwin_blur_manager: ptr org_kde_kwin_blur_manager
): pointer {.inline, cdecl.} =
  return wl_proxy_get_user_data(cast[ptr wl_proxy](org_kde_kwin_blur_manager))

proc org_kde_kwin_blur_manager_get_version*(
    org_kde_kwin_blur_manager: ptr org_kde_kwin_blur_manager
): uint32 {.inline, cdecl.} =
  return wl_proxy_get_version(cast[ptr wl_proxy](org_kde_kwin_blur_manager))

##  @ingroup iface_org_kde_kwin_blur_manager

proc org_kde_kwin_blur_manager_destroy*(
    org_kde_kwin_blur_manager: ptr org_kde_kwin_blur_manager
) {.inline, cdecl.} =
  wl_proxy_destroy(cast[ptr wl_proxy](org_kde_kwin_blur_manager))

##
##  @ingroup iface_org_kde_kwin_blur_manager
##

proc org_kde_kwin_blur_manager_create*(
    org_kde_kwin_blur_manager: ptr org_kde_kwin_blur_manager, surface: ptr wl_surface
): ptr org_kde_kwin_blur {.inline, cdecl.} =
  var id: ptr wl_proxy
  id = wl_proxy_marshal_flags(
    cast[ptr wl_proxy](org_kde_kwin_blur_manager),
    ORG_KDE_KWIN_BLUR_MANAGER_CREATE,
    addr(org_kde_kwin_blur_interface),
    wl_proxy_get_version(cast[ptr wl_proxy](org_kde_kwin_blur_manager)),
    0,
    nil,
    surface,
  )
  return cast[ptr org_kde_kwin_blur](id)

##
##  @ingroup iface_org_kde_kwin_blur_manager
##

proc org_kde_kwin_blur_manager_unset*(
    org_kde_kwin_blur_manager: ptr org_kde_kwin_blur_manager, surface: ptr wl_surface
) {.inline, cdecl.} =
  wl_proxy_marshal_flags(
    cast[ptr wl_proxy](org_kde_kwin_blur_manager),
    ORG_KDE_KWIN_BLUR_MANAGER_UNSET,
    nil,
    wl_proxy_get_version(cast[ptr wl_proxy](org_kde_kwin_blur_manager)),
    0,
    surface,
  )

const
  ORG_KDE_KWIN_BLUR_COMMIT* = 0
  ORG_KDE_KWIN_BLUR_SET_REGION* = 1
  ORG_KDE_KWIN_BLUR_RELEASE* = 2

##
##  @ingroup iface_org_kde_kwin_blur
##

const ORG_KDE_KWIN_BLUR_COMMIT_SINCE_VERSION* = 1

##
##  @ingroup iface_org_kde_kwin_blur
##

const ORG_KDE_KWIN_BLUR_SET_REGION_SINCE_VERSION* = 1

##
##  @ingroup iface_org_kde_kwin_blur
##

const ORG_KDE_KWIN_BLUR_RELEASE_SINCE_VERSION* = 1

##  @ingroup iface_org_kde_kwin_blur

proc org_kde_kwin_blur_set_user_data*(
    org_kde_kwin_blur: ptr org_kde_kwin_blur, user_data: pointer
) {.inline, cdecl.} =
  wl_proxy_set_user_data(cast[ptr wl_proxy](org_kde_kwin_blur), user_data)

##  @ingroup iface_org_kde_kwin_blur

proc org_kde_kwin_blur_get_user_data*(
    org_kde_kwin_blur: ptr org_kde_kwin_blur
): pointer {.inline, cdecl.} =
  return wl_proxy_get_user_data(cast[ptr wl_proxy](org_kde_kwin_blur))

proc org_kde_kwin_blur_get_version*(
    org_kde_kwin_blur: ptr org_kde_kwin_blur
): uint32 {.inline, cdecl.} =
  return wl_proxy_get_version(cast[ptr wl_proxy](org_kde_kwin_blur))

##  @ingroup iface_org_kde_kwin_blur

proc org_kde_kwin_blur_destroy*(
    org_kde_kwin_blur: ptr org_kde_kwin_blur
) {.inline, cdecl.} =
  wl_proxy_destroy(cast[ptr wl_proxy](org_kde_kwin_blur))

##
##  @ingroup iface_org_kde_kwin_blur
##

proc org_kde_kwin_blur_commit*(
    org_kde_kwin_blur: ptr org_kde_kwin_blur
) {.inline, cdecl.} =
  wl_proxy_marshal_flags(
    cast[ptr wl_proxy](org_kde_kwin_blur),
    ORG_KDE_KWIN_BLUR_COMMIT,
    nil,
    wl_proxy_get_version(cast[ptr wl_proxy](org_kde_kwin_blur)),
    0,
  )

##
##  @ingroup iface_org_kde_kwin_blur
##

proc org_kde_kwin_blur_set_region*(
    org_kde_kwin_blur: ptr org_kde_kwin_blur, region: ptr wl_region
) {.inline, cdecl.} =
  wl_proxy_marshal_flags(
    cast[ptr wl_proxy](org_kde_kwin_blur),
    ORG_KDE_KWIN_BLUR_SET_REGION,
    nil,
    wl_proxy_get_version(cast[ptr wl_proxy](org_kde_kwin_blur)),
    0,
    region,
  )

##
##  @ingroup iface_org_kde_kwin_blur
##

proc org_kde_kwin_blur_release*(
    org_kde_kwin_blur: ptr org_kde_kwin_blur
) {.inline, cdecl.} =
  wl_proxy_marshal_flags(
    cast[ptr wl_proxy](org_kde_kwin_blur),
    ORG_KDE_KWIN_BLUR_RELEASE,
    nil,
    wl_proxy_get_version(cast[ptr wl_proxy](org_kde_kwin_blur)),
    WL_MARSHAL_FLAG_DESTROY,
  )
