## Wrapper around `ext_idle_notifier_v1` (`IdleNotifier`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, ext_idle_notify_v1]
import pkg/nayland/types/protocols/core/prelude
import pkg/nayland/types/protocols/ext_idle_notify/notification
# wrapgen: begin emitting interface structures
type
  IdleNotifierObj* = object
    handle*: ptr ext_idle_notifier_v1

  IdleNotifier* = ref IdleNotifierObj
    ## =====
    ## idle notification manager
    ## =====
    ## This interface allows clients to monitor user idle status. After binding to this global, clients can create ext_idle_notification_v1 objects to get notified when the user is idle for a given amount of time.

proc `=destroy`*(obj: IdleNotifierObj) =
  ## =====
  ## destroy the manager
  ## =====
  ## Destroy the manager object. All objects created via this interface remain valid.
  ext_idle_notifier_v1_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initIdleNotifier*(raw: ptr ext_idle_notifier_v1 | pointer): IdleNotifier =
  ## Instantiate a IdleNotifier using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initIdleNotifier() was given an uninitialized handle!")

  IdleNotifier(handle: cast[ptr ext_idle_notifier_v1](raw))

func newIdleNotifier*(raw: ptr ext_idle_notifier_v1): IdleNotifier =
  ## Instantiate a IdleNotifier using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newIdleNotifier() was given an uninitialized handle!")

  IdleNotifier(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc getIdleNotification*(
    obj: IdleNotifier, Timeout: uint32, Seat: Seat
): IdleNotification =
  ## =====
  ## create a notification object
  ## =====
  ## Create a new idle notification object. The notification object has a minimum timeout duration and is tied to a seat. The client will be notified if the seat is inactive for at least the provided timeout. See ext_idle_notification_v1 for more details. A zero timeout is valid and means the client wants to be notified as soon as possible when the seat is inactive.
  initIdleNotification(
    ext_idle_notifier_v1_get_idle_notification(obj.handle, Timeout, Seat.handle)
  )

proc getInputIdleNotification*(
    obj: IdleNotifier, Timeout: uint32, Seat: Seat
): IdleNotification =
  ## =====
  ## create a notification object
  ## =====
  ## Create a new idle notification object to track input from the user, such as keyboard and mouse movement. Because this object is meant to track user input alone, it ignores idle inhibitors. The notification object has a minimum timeout duration and is tied to a seat. The client will be notified if the seat is inactive for at least the provided timeout. See ext_idle_notification_v1 for more details. A zero timeout is valid and means the client wants to be notified as soon as possible when the seat is inactive.
  initIdleNotification(
    ext_idle_notifier_v1_get_input_idle_notification(obj.handle, Timeout, Seat.handle)
  )

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
