## Wrapper around `ext_idle_notification_v1` (`IdleNotification`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, ext_idle_notify_v1]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  IdleNotificationObj* = object
    handle*: ptr ext_idle_notification_v1
    payload: IdleNotificationPayload

  IdleNotification* = ref IdleNotificationObj
    ## =====
    ## idle notification
    ## =====
    ## This interface is used by the compositor to send idle notification events to clients. Initially the notification object is not idle. The notification object becomes idle when no user activity has happened for at least the timeout duration, starting from the creation of the notification object. User activity may include input events or a presence sensor, but is compositor-specific. How this notification responds to idle inhibitors depends on how it was constructed. If constructed from the get_idle_notification request, then if an idle inhibitor is active (e.g. another client has created a zwp_idle_inhibitor_v1 on a visible surface), the compositor must not make the notification object idle. However, if constructed from the get_input_idle_notification request, then idle inhibitors are ignored, and only input from the user, e.g. from a keyboard or mouse, counts as activity. When the notification object becomes idle, an idled event is sent. When user activity starts again, the notification object stops being idle, a resumed event is sent and the timeout is restarted.

  IdleNotificationIdledCallback* = proc()
  IdleNotificationResumedCallback* = proc()
  IdleNotificationPayload = ref object
    idledCb: IdleNotificationIdledCallback
    resumedCb: IdleNotificationResumedCallback

proc `=destroy`*(obj: IdleNotificationObj) =
  ## =====
  ## destroy the notification object
  ## =====
  ## Destroy the notification object.
  ext_idle_notification_v1_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initIdleNotification*(
    raw: ptr ext_idle_notification_v1 | pointer
): IdleNotification =
  ## Instantiate a IdleNotification using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initIdleNotification() was given an uninitialized handle!")

  IdleNotification(
    handle: cast[ptr ext_idle_notification_v1](raw), payload: IdleNotificationPayload()
  )

func newIdleNotification*(raw: ptr ext_idle_notification_v1): IdleNotification =
  ## Instantiate a IdleNotification using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newIdleNotification() was given an uninitialized handle!")

  IdleNotification(handle: raw, payload: IdleNotificationPayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = ext_idle_notification_v1_listener(
  idled: proc(data: pointer, this: ptr ext_idle_notification_v1) {.cdecl.} =
    let payload = cast[IdleNotificationPayload](data)
    if payload.idledCb == nil:
      write(stderr, "[nayland] handler not attached for event 'idled'!\n")
      return

    payload.idledCb(),
  resumed: proc(data: pointer, this: ptr ext_idle_notification_v1) {.cdecl.} =
    let payload = cast[IdleNotificationPayload](data)
    if payload.resumedCb == nil:
      write(stderr, "[nayland] handler not attached for event 'resumed'!\n")
      return

    payload.resumedCb(),
)
proc attachCallbacks*(obj: IdleNotification) =
  discard ext_idle_notification_v1_add_listener(
    obj.handle, listener.addr, cast[pointer](obj.payload)
  )

func `onIdled=`*(
    obj: IdleNotification, cb: IdleNotificationIdledCallback
) {.inline, raises: [].} =
  obj.payload.idledCb = cb
func `onResumed=`*(
    obj: IdleNotification, cb: IdleNotificationResumedCallback
) {.inline, raises: [].} =
  obj.payload.resumedCb = cb

# wrapgen: start emitting request wrappers

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
