## Wrapper around `wp_content_type_manager_v1` (`ContentTypeManager`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, content_type_v1]
import pkg/nayland/types/protocols/core/prelude
import pkg/nayland/types/protocols/content_type/typ
# wrapgen: begin emitting interface structures
type
  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    AlreadyConstructed = 0'u32 ## wl_surface already has a content type object

  ContentTypeManagerObj* = object
    handle*: ptr wp_content_type_manager_v1

  ContentTypeManager* = ref ContentTypeManagerObj
    ## =====
    ## surface content type manager
    ## =====
    ## This interface allows a client to describe the kind of content a surface will display, to allow the compositor to optimize its behavior for it. Warning! The protocol described in this file is currently in the testing phase. Backward compatible changes may be added together with the corresponding interface version bump. Backward incompatible changes can only be done by creating a new major version of the extension.

proc `=destroy`*(obj: ContentTypeManagerObj) =
  ## =====
  ## destroy the content type manager object
  ## =====
  ## Destroy the content type manager. This doesn't destroy objects created with the manager.
  wp_content_type_manager_v1_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initContentTypeManager*(
    raw: ptr wp_content_type_manager_v1 | pointer
): ContentTypeManager =
  ## Instantiate a ContentTypeManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initContentTypeManager() was given an uninitialized handle!"
    )

  ContentTypeManager(handle: cast[ptr wp_content_type_manager_v1](raw))

func newContentTypeManager*(raw: ptr wp_content_type_manager_v1): ContentTypeManager =
  ## Instantiate a ContentTypeManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: newContentTypeManager() was given an uninitialized handle!"
    )

  ContentTypeManager(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc getSurfaceContentType*(obj: ContentTypeManager, Surface: Surface): ContentType =
  ## =====
  ## create a new content type object
  ## =====
  ## Create a new content type object associated with the given surface. Creating a wp_content_type_v1 from a wl_surface which already has one attached is a client error: already_constructed.
  initContentType(
    wp_content_type_manager_v1_get_surface_content_type(obj.handle, Surface.handle)
  )

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Error): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
