## Wrapper around `wp_content_type_v1` (`ContentType`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, content_type_v1]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Type* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## game content type
    ## =====
    ## The content type game describes a running game. Its content may be presented with reduced latency.
    None = 0'u32 ## 
    Photo = 1'u32 ## 
    Video = 2'u32 ## 
    Game = 3'u32 ## 

  ContentTypeObj* = object
    handle*: ptr wp_content_type_v1

  ContentType* = ref ContentTypeObj
    ## =====
    ## content type object for a surface
    ## =====
    ## The content type object allows the compositor to optimize for the kind of content shown on the surface. A compositor may for example use it to set relevant drm properties like "content type". The client may request to switch to another content type at any time. When the associated surface gets destroyed, this object becomes inert and the client should destroy it.

proc `=destroy`*(obj: ContentTypeObj) =
  ## =====
  ## destroy the content type object
  ## =====
  ## Switch back to not specifying the content type of this surface. This is equivalent to setting the content type to none, including double buffering semantics. See set_content_type for details.
  wp_content_type_v1_destroy(obj.handle)


# wrapgen: begin emitting constructor routines
func initContentType*(raw: ptr wp_content_type_v1 | pointer): ContentType =
  ## Instantiate a ContentType using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initContentType() was given an uninitialized handle!")
  
  ContentType(handle: cast[ptr wp_content_type_v1](raw))

func newContentType*(raw: ptr wp_content_type_v1): ContentType =
  ## Instantiate a ContentType using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newContentType() was given an uninitialized handle!")
  
  ContentType(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc setContentType*(obj: ContentType, ContentType: uint32) =
  ## =====
  ## specify the content type
  ## =====
  ## Set the surface content type. This informs the compositor that the client believes it is displaying buffers matching this content type. This is purely a hint for the compositor, which can be used to adjust its behavior or hardware settings to fit the presented content best. The content type is double-buffered state, see wl_surface.commit for details.
  wp_content_type_v1_set_content_type(obj.handle, ContentType)



# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Type): uint32 = cast[uint32](v)
# wrapgen: end emitting enum shims
