## Wrapper around `wp_viewporter` (`Viewporter`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, viewporter]
import
  pkg/nayland/types/protocols/core/prelude,
  pkg/nayland/types/protocols/viewporter/viewport
# wrapgen: begin emitting interface structures
type
  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    ViewportExists = 0'u32 ## the surface already has a viewport object associated

  ViewporterObj* = object
    handle*: ptr wp_viewporter

  Viewporter* = ref ViewporterObj
    ## =====
    ## surface cropping and scaling
    ## =====
    ## The global interface exposing surface cropping and scaling capabilities is used to instantiate an interface extension for a wl_surface object. This extended interface will then allow cropping and scaling the surface contents, effectively disconnecting the direct relationship between the buffer and the surface size.

proc `=destroy`*(obj: ViewporterObj) =
  ## =====
  ## unbind from the cropping and scaling interface
  ## =====
  ## Informs the server that the client will not be using this protocol object anymore. This does not affect any other objects, wp_viewport objects included.
  wp_viewporter_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initViewporter*(raw: ptr wp_viewporter | pointer): Viewporter =
  ## Instantiate a Viewporter using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initViewporter() was given an uninitialized handle!")

  Viewporter(handle: cast[ptr wp_viewporter](raw))

func newViewporter*(raw: ptr wp_viewporter): Viewporter =
  ## Instantiate a Viewporter using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newViewporter() was given an uninitialized handle!")

  Viewporter(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc getViewport*(obj: Viewporter, Surface: Surface): Viewport =
  ## =====
  ## extend surface interface for crop and scale
  ## =====
  ## Instantiate an interface extension for the given wl_surface to crop and scale its content. If the given wl_surface already has a wp_viewport object associated, the viewport_exists protocol error is raised.
  initViewport(wp_viewporter_get_viewport(obj.handle, Surface.handle))

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Error): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
