## Wrapper around `wp_fractional_scale_manager_v1` (`FractionalScaleManager`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, fractional_scale_v1]
import pkg/nayland/types/protocols/core/prelude
import pkg/nayland/types/protocols/fractional_scale/scale
# wrapgen: begin emitting interface structures
type
  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    FractionalScaleExists = 0'u32
      ## the surface already has a fractional_scale object associated

  FractionalScaleManagerObj* = object
    handle*: ptr wp_fractional_scale_manager_v1

  FractionalScaleManager* = ref FractionalScaleManagerObj
    ## =====
    ## fractional surface scale information
    ## =====
    ## A global interface for requesting surfaces to use fractional scales.

proc `=destroy`*(obj: FractionalScaleManagerObj) =
  ## =====
  ## unbind the fractional surface scale interface
  ## =====
  ## Informs the server that the client will not be using this protocol object anymore. This does not affect any other objects, wp_fractional_scale_v1 objects included.
  wp_fractional_scale_manager_v1_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initFractionalScaleManager*(
    raw: ptr wp_fractional_scale_manager_v1 | pointer
): FractionalScaleManager =
  ## Instantiate a FractionalScaleManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initFractionalScaleManager() was given an uninitialized handle!"
    )

  FractionalScaleManager(handle: cast[ptr wp_fractional_scale_manager_v1](raw))

func newFractionalScaleManager*(
    raw: ptr wp_fractional_scale_manager_v1
): FractionalScaleManager =
  ## Instantiate a FractionalScaleManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: newFractionalScaleManager() was given an uninitialized handle!"
    )

  FractionalScaleManager(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc getFractionalScale*(
    obj: FractionalScaleManager, Surface: Surface
): FractionalScale =
  ## =====
  ## extend surface interface for scale information
  ## =====
  ## Create an add-on object for the the wl_surface to let the compositor request fractional scales. If the given wl_surface already has a wp_fractional_scale_v1 object associated, the fractional_scale_exists protocol error is raised.
  initFractionalScale(
    wp_fractional_scale_manager_v1_get_fractional_scale(obj.handle, Surface.handle)
  )

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Error): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
