## Wrapper around `wp_fractional_scale_v1` (`FractionalScale`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, fractional_scale_v1]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  FractionalScaleObj* = object
    handle*: ptr wp_fractional_scale_v1
    payload: FractionalScalePayload

  FractionalScale* = ref FractionalScaleObj
    ## =====
    ## fractional scale interface to a wl_surface
    ## =====
    ## An additional interface to a wl_surface object which allows the compositor to inform the client of the preferred scale.

  FractionalScalePreferredScaleCallback* = proc(scale: uint32)
  FractionalScalePayload = ref object
    preferred_scaleCb: FractionalScalePreferredScaleCallback

proc `=destroy`*(obj: FractionalScaleObj) =
  ## =====
  ## remove surface scale information for surface
  ## =====
  ## Destroy the fractional scale object. When this object is destroyed, preferred_scale events will no longer be sent.
  wp_fractional_scale_v1_destroy(obj.handle)


# wrapgen: begin emitting constructor routines
func initFractionalScale*(raw: ptr wp_fractional_scale_v1 | pointer): FractionalScale =
  ## Instantiate a FractionalScale using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initFractionalScale() was given an uninitialized handle!")
  
  FractionalScale(handle: cast[ptr wp_fractional_scale_v1](raw), payload: FractionalScalePayload())

func newFractionalScale*(raw: ptr wp_fractional_scale_v1): FractionalScale =
  ## Instantiate a FractionalScale using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newFractionalScale() was given an uninitialized handle!")
  
  FractionalScale(handle: raw, payload: FractionalScalePayload())

# wrapgen: end emitting constructor routines


let listener {.global.} =
  wp_fractional_scale_v1_listener(
    preferred_scale: proc(data: pointer, this: ptr wp_fractional_scale_v1, scale: uint32) {.cdecl.} =
      let payload = cast[FractionalScalePayload](data)
      if payload.preferred_scaleCb == nil:
        write(stderr, "[nayland] handler not attached for event 'preferred_scale'!\n")
        return

      payload.preferred_scaleCb(scale)
)
proc attachCallbacks*(obj: FractionalScale) =
  discard wp_fractional_scale_v1_add_listener(obj.handle, listener.addr, cast[pointer](obj.payload))

func `onPreferredScale=`*(obj: FractionalScale, cb: FractionalScalePreferredScaleCallback) {.inline, raises: [].} =
  obj.payload.preferred_scaleCb = cb

# wrapgen: start emitting request wrappers


# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
