## Wrapper around `wp_presentation_feedback` (`PresentationFeedback`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, presentation_time]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Kind* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## presentation was done zero-copy
    ## =====
    ## The presentation of this update was done zero-copy. This means the buffer from the client was given to display hardware as is, without copying it. Compositing with OpenGL counts as copying, even if textured directly from the client buffer. Possible zero-copy cases include direct scanout of a fullscreen surface and a surface on a hardware overlay.
    Vsync = 1'u32 ## 
    HwClock = 2'u32 ## 
    HwCompletion = 4'u32 ## 
    ZeroCopy = 8'u32 ## 

  PresentationFeedbackObj* = object
    handle*: ptr wp_presentation_feedback
    payload: PresentationFeedbackPayload

  PresentationFeedback* = ref PresentationFeedbackObj
    ## =====
    ## presentation time feedback event
    ## =====
    ## A presentation_feedback object returns an indication that a wl_surface content update has become visible to the user. One object corresponds to one content update submission (wl_surface.commit). There are two possible outcomes: the content update is presented to the user, and a presentation timestamp delivered; or, the user did not see the content update because it was superseded or its surface destroyed, and the content update is discarded. Once a presentation_feedback object has delivered a 'presented' or 'discarded' event it is automatically destroyed.

  PresentationFeedbackSyncOutputCallback* = proc(output: Output)
  PresentationFeedbackPresentedCallback* = proc(
    tv_sec_hi: uint32,
    tv_sec_lo: uint32,
    tv_nsec: uint32,
    refresh: uint32,
    seq_hi: uint32,
    seq_lo: uint32,
    flags: uint32,
  )
  PresentationFeedbackDiscardedCallback* = proc()
  PresentationFeedbackPayload = ref object
    sync_outputCb: PresentationFeedbackSyncOutputCallback
    presentedCb: PresentationFeedbackPresentedCallback
    discardedCb: PresentationFeedbackDiscardedCallback

# wrapgen: begin emitting constructor routines
func initPresentationFeedback*(
    raw: ptr wp_presentation_feedback | pointer
): PresentationFeedback =
  ## Instantiate a PresentationFeedback using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initPresentationFeedback() was given an uninitialized handle!"
    )

  PresentationFeedback(
    handle: cast[ptr wp_presentation_feedback](raw),
    payload: PresentationFeedbackPayload(),
  )

func newPresentationFeedback*(raw: ptr wp_presentation_feedback): PresentationFeedback =
  ## Instantiate a PresentationFeedback using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: newPresentationFeedback() was given an uninitialized handle!"
    )

  PresentationFeedback(handle: raw, payload: PresentationFeedbackPayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = wp_presentation_feedback_listener(
  sync_output: proc(
      data: pointer, this: ptr wp_presentation_feedback, output: ptr wl_output
  ) {.cdecl.} =
    let payload = cast[PresentationFeedbackPayload](data)
    if payload.sync_outputCb == nil:
      write(stderr, "[nayland] handler not attached for event 'sync_output'!\n")
      return

    payload.sync_outputCb(initOutput(output)),
  presented: proc(
      data: pointer,
      this: ptr wp_presentation_feedback,
      tv_sec_hi: uint32,
      tv_sec_lo: uint32,
      tv_nsec: uint32,
      refresh: uint32,
      seq_hi: uint32,
      seq_lo: uint32,
      flags: uint32,
  ) {.cdecl.} =
    let payload = cast[PresentationFeedbackPayload](data)
    if payload.presentedCb == nil:
      write(stderr, "[nayland] handler not attached for event 'presented'!\n")
      return

    payload.presentedCb(tv_sec_hi, tv_sec_lo, tv_nsec, refresh, seq_hi, seq_lo, flags),
  discarded: proc(data: pointer, this: ptr wp_presentation_feedback) {.cdecl.} =
    let payload = cast[PresentationFeedbackPayload](data)
    if payload.discardedCb == nil:
      write(stderr, "[nayland] handler not attached for event 'discarded'!\n")
      return

    payload.discardedCb(),
)
proc attachCallbacks*(obj: PresentationFeedback) =
  discard wp_presentation_feedback_add_listener(
    obj.handle, listener.addr, cast[pointer](obj.payload)
  )

func `onSyncOutput=`*(
    obj: PresentationFeedback, cb: PresentationFeedbackSyncOutputCallback
) {.inline, raises: [].} =
  obj.payload.sync_outputCb = cb
func `onPresented=`*(
    obj: PresentationFeedback, cb: PresentationFeedbackPresentedCallback
) {.inline, raises: [].} =
  obj.payload.presentedCb = cb
func `onDiscarded=`*(
    obj: PresentationFeedback, cb: PresentationFeedbackDiscardedCallback
) {.inline, raises: [].} =
  obj.payload.discardedCb = cb

# wrapgen: start emitting request wrappers

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Kind): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
