## Wrapper around `wp_presentation` (`Presentation`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, presentation_time]
import pkg/nayland/types/protocols/core/prelude
import pkg/nayland/types/protocols/presentation_time/feedback
# wrapgen: begin emitting interface structures
type
  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## fatal presentation errors
    ## =====
    ## These fatal protocol errors may be emitted in response to illegal presentation requests.
    InvalidTimestamp = 0'u32 ## invalid value in tv_nsec
    InvalidFlag = 1'u32 ## invalid flag

  PresentationObj* = object
    handle*: ptr wp_presentation
    payload: PresentationPayload

  Presentation* = ref PresentationObj
    ## =====
    ## timed presentation related wl_surface requests
    ## =====
    ## The main feature of this interface is accurate presentation timing feedback to ensure smooth video playback while maintaining audio/video synchronization. Some features use the concept of a presentation clock, which is defined in the presentation.clock_id event. A content update for a wl_surface is submitted by a wl_surface.commit request. Request 'feedback' associates with the wl_surface.commit and provides feedback on the content update, particularly the final realized presentation time.

  PresentationClockIdCallback* = proc(clk_id: uint32)
  PresentationPayload = ref object
    clock_idCb: PresentationClockIdCallback

proc `=destroy`*(obj: PresentationObj) =
  ## =====
  ## unbind from the presentation interface
  ## =====
  ## Informs the server that the client will no longer be using this protocol object. Existing objects created by this object are not affected.
  wp_presentation_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initPresentation*(raw: ptr wp_presentation | pointer): Presentation =
  ## Instantiate a Presentation using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initPresentation() was given an uninitialized handle!")

  Presentation(handle: cast[ptr wp_presentation](raw), payload: PresentationPayload())

func newPresentation*(raw: ptr wp_presentation): Presentation =
  ## Instantiate a Presentation using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newPresentation() was given an uninitialized handle!")

  Presentation(handle: raw, payload: PresentationPayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = wp_presentation_listener(
  clock_id: proc(data: pointer, this: ptr wp_presentation, clk_id: uint32) {.cdecl.} =
    let payload = cast[PresentationPayload](data)
    if payload.clock_idCb == nil:
      write(stderr, "[nayland] handler not attached for event 'clock_id'!\n")
      return

    payload.clock_idCb(clk_id)
)
proc attachCallbacks*(obj: Presentation) =
  discard
    wp_presentation_add_listener(obj.handle, listener.addr, cast[pointer](obj.payload))

func `onClockId=`*(
    obj: Presentation, cb: PresentationClockIdCallback
) {.inline, raises: [].} =
  obj.payload.clock_idCb = cb

# wrapgen: start emitting request wrappers

proc feedback*(obj: Presentation, Surface: Surface): PresentationFeedback =
  ## =====
  ## request presentation feedback information
  ## =====
  ## Request presentation feedback for the current content submission on the given surface. This creates a new presentation_feedback object, which will deliver the feedback information once. If multiple presentation_feedback objects are created for the same submission, they will all deliver the same information. For details on what information is returned, see the presentation_feedback interface.
  initPresentationFeedback(fnwp_presentation_feedback(obj.handle, Surface.handle))

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Error): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
