## Wrapper around `xdg_wm_base` (`WmBase`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, xdg_shell]
import pkg/nayland/types/protocols/core/prelude
import pkg/nayland/types/protocols/xdg_shell/[surface, toplevel, positioner]
# wrapgen: begin emitting interface structures
type
  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    Role = 0'u32 ## given wl_surface has another role
    DefunctSurfaces = 1'u32 ## xdg_wm_base was destroyed before children
    NotTheTopmostPopup = 2'u32 ## the client tried to map or destroy a non-topmost popup
    InvalidPopupParent = 3'u32 ## the client specified an invalid popup parent surface
    InvalidSurfaceState = 4'u32 ## the client provided an invalid surface state
    InvalidPositioner = 5'u32 ## the client provided an invalid positioner
    Unresponsive = 6'u32 ## the client didn’t respond to a ping event in time

  WmBaseObj* = object
    handle*: ptr xdg_wm_base
    payload: WmBasePayload

  WmBase* = ref WmBaseObj
    ## =====
    ## create desktop-style surfaces
    ## =====
    ## The xdg_wm_base interface is exposed as a global object enabling clients to turn their wl_surfaces into windows in a desktop environment. It defines the basic functionality needed for clients and the compositor to create windows that can be dragged, resized, maximized, etc, as well as creating transient windows such as popup menus.

  WmBasePingCallback* = proc(serial: uint32)
  WmBasePayload = ref object
    pingCb: WmBasePingCallback

proc `=destroy`*(obj: WmBaseObj) =
  ## =====
  ## destroy xdg_wm_base
  ## =====
  ## Destroy this xdg_wm_base object. Destroying a bound xdg_wm_base object while there are surfaces still alive created by this xdg_wm_base object instance is illegal and will result in a defunct_surfaces error.
  xdg_wm_base_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initWmBase*(raw: ptr xdg_wm_base | pointer): WmBase =
  ## Instantiate a WmBase using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initWmBase() was given an uninitialized handle!")

  WmBase(handle: cast[ptr xdg_wm_base](raw), payload: WmBasePayload())

func newWmBase*(raw: ptr xdg_wm_base): WmBase =
  ## Instantiate a WmBase using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newWmBase() was given an uninitialized handle!")

  WmBase(handle: raw, payload: WmBasePayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = xdg_wm_base_listener(
  ping: proc(data: pointer, this: ptr xdg_wm_base, serial: uint32) {.cdecl.} =
    let payload = cast[WmBasePayload](data)
    if payload.pingCb == nil:
      write(stderr, "[nayland] handler not attached for event 'ping'!\n")
      return

    payload.pingCb(serial)
)
proc attachCallbacks*(obj: WmBase) =
  discard
    xdg_wm_base_add_listener(obj.handle, listener.addr, cast[pointer](obj.payload))

func `onPing=`*(obj: WmBase, cb: WmBasePingCallback) {.inline, raises: [].} =
  obj.payload.pingCb = cb

# wrapgen: start emitting request wrappers

proc createPositioner*(obj: WmBase): Positioner =
  ## =====
  ## create a positioner object
  ## =====
  ## Create a positioner object. A positioner object is used to position surfaces relative to some parent surface. See the interface description and xdg_surface.get_popup for details.
  initPositioner(xdg_wm_base_create_positioner(obj.handle))

proc getXdgSurface*(obj: WmBase, Surface: Surface): XDGSurface =
  ## =====
  ## create a shell surface from a surface
  ## =====
  ## This creates an xdg_surface for the given surface. While xdg_surface itself is not a role, the corresponding surface may only be assigned a role extending xdg_surface, such as xdg_toplevel or xdg_popup. It is illegal to create an xdg_surface for a wl_surface which already has an assigned role and this will result in a role error. This creates an xdg_surface for the given surface. An xdg_surface is used as basis to define a role to a given surface, such as xdg_toplevel or xdg_popup. It also manages functionality shared between xdg_surface based surface roles. See the documentation of xdg_surface for more details about what an xdg_surface is and how it is used.
  initXDGSurface(xdg_wm_base_get_xdg_surface(obj.handle, Surface.handle))

proc pong*(obj: WmBase, Serial: uint32) =
  ## =====
  ## respond to a ping event
  ## =====
  ## A client must respond to a ping event with a pong request or the client may be deemed unresponsive. See xdg_wm_base.ping and xdg_wm_base.error.unresponsive.
  xdg_wm_base_pong(obj.handle, Serial)

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Error): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
