## Wrapper around `xdg_popup` (`Popup`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, xdg_shell]
import
  pkg/nayland/types/protocols/core/prelude,
  pkg/nayland/types/protocols/xdg_shell/positioner
# wrapgen: begin emitting interface structures
type
  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    InvalidGrab = 0'u32 ## tried to grab after being mapped

  PopupObj* = object
    handle*: ptr xdg_popup
    payload: PopupPayload

  Popup* = ref PopupObj
    ## =====
    ## short-lived, popup surfaces for menus
    ## =====
    ## A popup surface is a short-lived, temporary surface. It can be used to implement for example menus, popovers, tooltips and other similar user interface concepts. A popup can be made to take an explicit grab. See xdg_popup.grab for details. When the popup is dismissed, a popup_done event will be sent out, and at the same time the surface will be unmapped. See the xdg_popup.popup_done event for details. Explicitly destroying the xdg_popup object will also dismiss the popup and unmap the surface. Clients that want to dismiss the popup when another surface of their own is clicked should dismiss the popup using the destroy request. A newly created xdg_popup will be stacked on top of all previously created xdg_popup surfaces associated with the same xdg_toplevel. The parent of an xdg_popup must be mapped (see the xdg_surface description) before the xdg_popup itself. The client must call wl_surface.commit on the corresponding wl_surface for the xdg_popup state to take effect.

  PopupConfigureCallback* = proc(x: int32, y: int32, width: int32, height: int32)
  PopupPopupDoneCallback* = proc()
  PopupRepositionedCallback* = proc(token: uint32)
  PopupPayload = ref object
    configureCb: PopupConfigureCallback
    popup_doneCb: PopupPopupDoneCallback
    repositionedCb: PopupRepositionedCallback

proc `=destroy`*(obj: PopupObj) =
  ## =====
  ## remove xdg_popup interface
  ## =====
  ## This destroys the popup. Explicitly destroying the xdg_popup object will also dismiss the popup, and unmap the surface. If this xdg_popup is not the "topmost" popup, the xdg_wm_base.not_the_topmost_popup protocol error will be sent.
  xdg_popup_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initPopup*(raw: ptr xdg_popup | pointer): Popup =
  ## Instantiate a Popup using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initPopup() was given an uninitialized handle!")

  Popup(handle: cast[ptr xdg_popup](raw), payload: PopupPayload())

func newPopup*(raw: ptr xdg_popup): Popup =
  ## Instantiate a Popup using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newPopup() was given an uninitialized handle!")

  Popup(handle: raw, payload: PopupPayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = xdg_popup_listener(
  configure: proc(
      data: pointer,
      this: ptr xdg_popup,
      x: int32,
      y: int32,
      width: int32,
      height: int32,
  ) {.cdecl.} =
    let payload = cast[PopupPayload](data)
    if payload.configureCb == nil:
      write(stderr, "[nayland] handler not attached for event 'configure'!\n")
      return

    payload.configureCb(x, y, width, height),
  popup_done: proc(data: pointer, this: ptr xdg_popup) {.cdecl.} =
    let payload = cast[PopupPayload](data)
    if payload.popup_doneCb == nil:
      write(stderr, "[nayland] handler not attached for event 'popup_done'!\n")
      return

    payload.popup_doneCb(),
  repositioned: proc(data: pointer, this: ptr xdg_popup, token: uint32) {.cdecl.} =
    let payload = cast[PopupPayload](data)
    if payload.repositionedCb == nil:
      write(stderr, "[nayland] handler not attached for event 'repositioned'!\n")
      return

    payload.repositionedCb(token),
)
proc attachCallbacks*(obj: Popup) =
  discard xdg_popup_add_listener(obj.handle, listener.addr, cast[pointer](obj.payload))

func `onConfigure=`*(obj: Popup, cb: PopupConfigureCallback) {.inline, raises: [].} =
  obj.payload.configureCb = cb
func `onPopupDone=`*(obj: Popup, cb: PopupPopupDoneCallback) {.inline, raises: [].} =
  obj.payload.popup_doneCb = cb
func `onRepositioned=`*(
    obj: Popup, cb: PopupRepositionedCallback
) {.inline, raises: [].} =
  obj.payload.repositionedCb = cb

# wrapgen: start emitting request wrappers

proc grab*(obj: Popup, Seat: Seat, Serial: uint32) =
  ## =====
  ## make the popup take an explicit grab
  ## =====
  ## This request makes the created popup take an explicit grab. An explicit grab will be dismissed when the user dismisses the popup, or when the client destroys the xdg_popup. This can be done by the user clicking outside the surface, using the keyboard, or even locking the screen through closing the lid or a timeout. If the compositor denies the grab, the popup will be immediately dismissed. This request must be used in response to some sort of user action like a button press, key press, or touch down event. The serial number of the event should be passed as 'serial'. The parent of a grabbing popup must either be an xdg_toplevel surface or another xdg_popup with an explicit grab. If the parent is another xdg_popup it means that the popups are nested, with this popup now being the topmost popup. Nested popups must be destroyed in the reverse order they were created in, e.g. the only popup you are allowed to destroy at all times is the topmost one. When compositors choose to dismiss a popup, they may dismiss every nested grabbing popup as well. When a compositor dismisses popups, it will follow the same dismissing order as required from the client. If the topmost grabbing popup is destroyed, the grab will be returned to the parent of the popup, if that parent previously had an explicit grab. If the parent is a grabbing popup which has already been dismissed, this popup will be immediately dismissed. If the parent is a popup that did not take an explicit grab, an error will be raised. During a popup grab, the client owning the grab will receive pointer and touch events for all their surfaces as normal (similar to an "owner-events" grab in X11 parlance), while the top most grabbing popup will always have keyboard focus.
  xdg_popup_grab(obj.handle, Seat.handle, Serial)

proc reposition*(obj: Popup, Positioner: Positioner, Token: uint32) =
  ## =====
  ## recalculate the popup's location
  ## =====
  ## Reposition an already-mapped popup. The popup will be placed given the details in the passed xdg_positioner object, and a xdg_popup.repositioned followed by xdg_popup.configure and xdg_surface.configure will be emitted in response. Any parameters set by the previous positioner will be discarded. The passed token will be sent in the corresponding xdg_popup.repositioned event. The new popup position will not take effect until the corresponding configure event is acknowledged by the client. See xdg_popup.repositioned for details. The token itself is opaque, and has no other special meaning. If multiple reposition requests are sent, the compositor may skip all but the last one. If the popup is repositioned in response to a configure event for its parent, the client should send an xdg_positioner.set_parent_configure and possibly an xdg_positioner.set_parent_size request to allow the compositor to properly constrain the popup. If the popup is repositioned together with a parent that is being resized, but not in response to a configure event, the client should send an xdg_positioner.set_parent_size request.
  xdg_popup_reposition(obj.handle, Positioner.handle, Token)

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Error): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
