## Wrapper around `xdg_positioner` (`Positioner`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, xdg_shell]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    InvalidInput = 0'u32 ## invalid input provided

  Anchor* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    None = 0'u32 ## 
    Top = 1'u32 ## 
    Bottom = 2'u32 ## 
    Left = 3'u32 ## 
    Right = 4'u32 ## 
    TopLeft = 5'u32 ## 
    BottomLeft = 6'u32 ## 
    TopRight = 7'u32 ## 
    BottomRight = 8'u32 ## 

  Gravity* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    None = 0'u32 ## 
    Top = 1'u32 ## 
    Bottom = 2'u32 ## 
    Left = 3'u32 ## 
    Right = 4'u32 ## 
    TopLeft = 5'u32 ## 
    BottomLeft = 6'u32 ## 
    TopRight = 7'u32 ## 
    BottomRight = 8'u32 ## 

  Constraint_adjustment* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## vertically resize the surface
    ## =====
    ## Resize the surface vertically so that it is completely unconstrained.
    None = 0'u32 ## 
    SlideX = 1'u32 ## 
    SlideY = 2'u32 ## 
    FlipX = 4'u32 ## 
    FlipY = 8'u32 ## 
    ResizeX = 16'u32 ## 
    ResizeY = 32'u32 ## 

  PositionerObj* = object
    handle*: ptr xdg_positioner

  Positioner* = ref PositionerObj
    ## =====
    ## child surface positioner
    ## =====
    ## The xdg_positioner provides a collection of rules for the placement of a child surface relative to a parent surface. Rules can be defined to ensure the child surface remains within the visible area's borders, and to specify how the child surface changes its position, such as sliding along an axis, or flipping around a rectangle. These positioner-created rules are constrained by the requirement that a child surface must intersect with or be at least partially adjacent to its parent surface. See the various requests for details about possible rules. At the time of the request, the compositor makes a copy of the rules specified by the xdg_positioner. Thus, after the request is complete the xdg_positioner object can be destroyed or reused; further changes to the object will have no effect on previous usages. For an xdg_positioner object to be considered complete, it must have a non-zero size set by set_size, and a non-zero anchor rectangle set by set_anchor_rect. Passing an incomplete xdg_positioner object when positioning a surface raises an invalid_positioner error.

proc `=destroy`*(obj: PositionerObj) =
  ## =====
  ## destroy the xdg_positioner object
  ## =====
  ## Notify the compositor that the xdg_positioner will no longer be used.
  xdg_positioner_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initPositioner*(raw: ptr xdg_positioner | pointer): Positioner =
  ## Instantiate a Positioner using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initPositioner() was given an uninitialized handle!")

  Positioner(handle: cast[ptr xdg_positioner](raw))

func newPositioner*(raw: ptr xdg_positioner): Positioner =
  ## Instantiate a Positioner using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newPositioner() was given an uninitialized handle!")

  Positioner(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc setSize*(obj: Positioner, Width: int32, Height: int32) =
  ## =====
  ## set the size of the to-be positioned rectangle
  ## =====
  ## Set the size of the surface that is to be positioned with the positioner object. The size is in surface-local coordinates and corresponds to the window geometry. See xdg_surface.set_window_geometry. If a zero or negative size is set the invalid_input error is raised.
  xdg_positioner_set_size(obj.handle, Width, Height)

proc setAnchorRect*(obj: Positioner, X: int32, Y: int32, Width: int32, Height: int32) =
  ## =====
  ## set the anchor rectangle within the parent surface
  ## =====
  ## Specify the anchor rectangle within the parent surface that the child surface will be placed relative to. The rectangle is relative to the window geometry as defined by xdg_surface.set_window_geometry of the parent surface. When the xdg_positioner object is used to position a child surface, the anchor rectangle may not extend outside the window geometry of the positioned child's parent surface. If a negative size is set the invalid_input error is raised.
  xdg_positioner_set_anchor_rect(obj.handle, X, Y, Width, Height)

proc setAnchor*(obj: Positioner, Anchor: uint32) =
  ## =====
  ## set anchor rectangle anchor
  ## =====
  ## Defines the anchor point for the anchor rectangle. The specified anchor is used derive an anchor point that the child surface will be positioned relative to. If a corner anchor is set (e.g. 'top_left' or 'bottom_right'), the anchor point will be at the specified corner; otherwise, the derived anchor point will be centered on the specified edge, or in the center of the anchor rectangle if no edge is specified.
  xdg_positioner_set_anchor(obj.handle, Anchor)

proc setGravity*(obj: Positioner, Gravity: uint32) =
  ## =====
  ## set child surface gravity
  ## =====
  ## Defines in what direction a surface should be positioned, relative to the anchor point of the parent surface. If a corner gravity is specified (e.g. 'bottom_right' or 'top_left'), then the child surface will be placed towards the specified gravity; otherwise, the child surface will be centered over the anchor point on any axis that had no gravity specified. If the gravity is not in the ‘gravity’ enum, an invalid_input error is raised.
  xdg_positioner_set_gravity(obj.handle, Gravity)

proc setConstraintAdjustment*(obj: Positioner, ConstraintAdjustment: uint32) =
  ## =====
  ## set the adjustment to be done when constrained
  ## =====
  ## Specify how the window should be positioned if the originally intended position caused the surface to be constrained, meaning at least partially outside positioning boundaries set by the compositor. The adjustment is set by constructing a bitmask describing the adjustment to be made when the surface is constrained on that axis. If no bit for one axis is set, the compositor will assume that the child surface should not change its position on that axis when constrained. If more than one bit for one axis is set, the order of how adjustments are applied is specified in the corresponding adjustment descriptions. The default adjustment is none.
  xdg_positioner_set_constraint_adjustment(obj.handle, ConstraintAdjustment)

proc setOffset*(obj: Positioner, X: int32, Y: int32) =
  ## =====
  ## set surface position offset
  ## =====
  ## Specify the surface position offset relative to the position of the anchor on the anchor rectangle and the anchor on the surface. For example if the anchor of the anchor rectangle is at (x, y), the surface has the gravity bottom|right, and the offset is (ox, oy), the calculated surface position will be (x + ox, y + oy). The offset position of the surface is the one used for constraint testing. See set_constraint_adjustment. An example use case is placing a popup menu on top of a user interface element, while aligning the user interface element of the parent surface with some user interface element placed somewhere in the popup surface.
  xdg_positioner_set_offset(obj.handle, X, Y)

proc setReactive*(obj: Positioner) =
  ## =====
  ## continuously reconstrain the surface
  ## =====
  ## When set reactive, the surface is reconstrained if the conditions used for constraining changed, e.g. the parent window moved. If the conditions changed and the popup was reconstrained, an xdg_popup.configure event is sent with updated geometry, followed by an xdg_surface.configure event.
  xdg_positioner_set_reactive(obj.handle)

proc setParentSize*(obj: Positioner, ParentWidth: int32, ParentHeight: int32) =
  ## =====
  ## 
  ## =====
  ## Set the parent window geometry the compositor should use when positioning the popup. The compositor may use this information to determine the future state the popup should be constrained using. If this doesn't match the dimension of the parent the popup is eventually positioned against, the behavior is undefined. The arguments are given in the surface-local coordinate space.
  xdg_positioner_set_parent_size(obj.handle, ParentWidth, ParentHeight)

proc setParentConfigure*(obj: Positioner, Serial: uint32) =
  ## =====
  ## set parent configure this is a response to
  ## =====
  ## Set the serial of an xdg_surface.configure event this positioner will be used in response to. The compositor may use this information together with set_parent_size to determine what future state the popup should be constrained using.
  xdg_positioner_set_parent_configure(obj.handle, Serial)

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Error): uint32 =
  cast[uint32](v)

converter shim1*(v: Anchor): uint32 =
  cast[uint32](v)

converter shim2*(v: Gravity): uint32 =
  cast[uint32](v)

converter shim3*(v: Constraint_adjustment): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
