## Wrapper around `xdg_toplevel` (`Toplevel`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, xdg_shell], pkg/nayland/bindings/libwayland
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    InvalidResizeEdge = 0'u32
      ## provided value is not a valid variant of the resize_edge enum
    InvalidParent = 1'u32 ## invalid parent toplevel
    InvalidSize = 2'u32 ## client provided an invalid min or max size

  Resize_edge* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## edge values for resizing
    ## =====
    ## These values are used to indicate which edge of a surface is being dragged in a resize operation.
    None = 0'u32 ## 
    Top = 1'u32 ## 
    Bottom = 2'u32 ## 
    Left = 4'u32 ## 
    TopLeft = 5'u32 ## 
    BottomLeft = 6'u32 ## 
    Right = 8'u32 ## 
    TopRight = 9'u32 ## 
    BottomRight = 10'u32 ## 

  State* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## the surface’s bottom edge is tiled
    ## =====
    ## The bottom edge of the window is currently constrained, meaning it shouldn't attempt to resize from that edge. It can for example mean it's tiled next to a monitor edge on the constrained side of the window.
    Maximized = 1'u32 ## the surface is maximized
    Fullscreen = 2'u32 ## the surface is fullscreen
    Resizing = 3'u32 ## the surface is being resized
    Activated = 4'u32 ## the surface is now activated
    TiledLeft = 5'u32 ## 
    TiledRight = 6'u32 ## 
    TiledTop = 7'u32 ## 
    TiledBottom = 8'u32 ## 
    Suspended = 9'u32 ## 
    ConstrainedLeft = 10'u32 ## 
    ConstrainedRight = 11'u32 ## 
    ConstrainedTop = 12'u32 ## 
    ConstrainedBottom = 13'u32 ## 

  Wm_capabilities* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    WindowMenu = 1'u32 ## show_window_menu is available
    Maximize = 2'u32 ## set_maximized and unset_maximized are available
    Fullscreen = 3'u32 ## set_fullscreen and unset_fullscreen are available
    Minimize = 4'u32 ## set_minimized is available

  Toplevel* = ref ToplevelObj
    ## =====
    ## toplevel surface
    ## =====
    ## This interface defines an xdg_surface role which allows a surface to, among other things, set window-like properties such as maximize, fullscreen, and minimize, set application-specific metadata like title and id, and well as trigger user interactive operations such as interactive resize and move. A xdg_toplevel by default is responsible for providing the full intended visual representation of the toplevel, which depending on the window state, may mean things like a title bar, window controls and drop shadow. Unmapping an xdg_toplevel means that the surface cannot be shown by the compositor until it is explicitly mapped again. All active operations (e.g., move, resize) are canceled and all attributes (e.g. title, state, stacking, ...) are discarded for an xdg_toplevel surface when it is unmapped. The xdg_toplevel returns to the state it had right after xdg_surface.get_toplevel. The client can re-map the toplevel by performing a commit without any buffer attached, waiting for a configure event and handling it as usual (see xdg_surface description). Attaching a null buffer to a toplevel unmaps the surface.

  ToplevelConfigureCallback* = proc(width: int32, height: int32, states: seq[State])
  ToplevelCloseCallback* = proc()
  ToplevelConfigureBoundsCallback* = proc(width: int32, height: int32)
  ToplevelWmCapabilitiesCallback* = proc(capabilities: seq[WMCapabilities])
    # TODO: wrapgen should handle array types properly
  ToplevelPayload = ref object
    configureCb: ToplevelConfigureCallback
    closeCb: ToplevelCloseCallback
    configure_boundsCb: ToplevelConfigureBoundsCallback
    wm_capabilitiesCb: ToplevelWmCapabilitiesCallback

  ToplevelObj* = object
    handle*: ptr xdg_toplevel
    payload: ToplevelPayload

proc `=destroy`*(obj: ToplevelObj) =
  ## =====
  ## destroy the xdg_toplevel
  ## =====
  ## This request destroys the role surface and unmaps the surface; see "Unmapping" behavior in interface section for details.
  xdg_toplevel_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initToplevel*(raw: ptr xdg_toplevel | pointer): Toplevel =
  ## Instantiate a Toplevel using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initToplevel() was given an uninitialized handle!")

  Toplevel(handle: cast[ptr xdg_toplevel](raw), payload: ToplevelPayload())

func newToplevel*(raw: ptr xdg_toplevel): Toplevel =
  ## Instantiate a Toplevel using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newToplevel() was given an uninitialized handle!")

  Toplevel(handle: raw, payload: ToplevelPayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = xdg_toplevel_listener(
  configure: proc(
      data: pointer,
      this: ptr xdg_toplevel,
      width: int32,
      height: int32,
      states: ptr wl_array,
  ) {.cdecl.} =
    let payload = cast[ToplevelPayload](data)
    if payload.configureCb == nil:
      write(stderr, "[nayland] handler not attached for event 'configure'!\n")
      return

    payload.configureCb(width, height, shallowCopyArray(states, State)),
  close: proc(data: pointer, this: ptr xdg_toplevel) {.cdecl.} =
    let payload = cast[ToplevelPayload](data)
    if payload.closeCb == nil:
      write(stderr, "[nayland] handler not attached for event 'close'!\n")
      return

    payload.closeCb(),
  configure_bounds: proc(
      data: pointer, this: ptr xdg_toplevel, width: int32, height: int32
  ) {.cdecl.} =
    let payload = cast[ToplevelPayload](data)
    if payload.configure_boundsCb == nil:
      write(stderr, "[nayland] handler not attached for event 'configure_bounds'!\n")
      return

    payload.configure_boundsCb(width, height),
  wm_capabilities: proc(
      data: pointer, this: ptr xdg_toplevel, capabilities: ptr wl_array
  ) {.cdecl.} =
    let payload = cast[ToplevelPayload](data)
    if payload.wm_capabilitiesCb == nil:
      write(stderr, "[nayland] handler not attached for event 'wm_capabilities'!\n")
      return

    payload.wm_capabilitiesCb(shallowCopyArray(capabilities, WMCapabilities)),
)
proc attachCallbacks*(obj: Toplevel) =
  discard
    xdg_toplevel_add_listener(obj.handle, listener.addr, cast[pointer](obj.payload))

func `onConfigure=`*(
    obj: Toplevel, cb: ToplevelConfigureCallback
) {.inline, raises: [].} =
  obj.payload.configureCb = cb
func `onClose=`*(obj: Toplevel, cb: ToplevelCloseCallback) {.inline, raises: [].} =
  obj.payload.closeCb = cb
func `onConfigureBounds=`*(
    obj: Toplevel, cb: ToplevelConfigureBoundsCallback
) {.inline, raises: [].} =
  obj.payload.configure_boundsCb = cb
func `onWmCapabilities=`*(
    obj: Toplevel, cb: ToplevelWmCapabilitiesCallback
) {.inline, raises: [].} =
  obj.payload.wm_capabilitiesCb = cb

# wrapgen: start emitting request wrappers

proc setParent*(obj: Toplevel, Parent: Toplevel) =
  ## =====
  ## set the parent of this surface
  ## =====
  ## Set the "parent" of this surface. This surface should be stacked above the parent surface and all other ancestor surfaces. Parent surfaces should be set on dialogs, toolboxes, or other "auxiliary" surfaces, so that the parent is raised when the dialog is raised. Setting a null parent for a child surface unsets its parent. Setting a null parent for a surface which currently has no parent is a no-op. Only mapped surfaces can have child surfaces. Setting a parent which is not mapped is equivalent to setting a null parent. If a surface becomes unmapped, its children's parent is set to the parent of the now-unmapped surface. If the now-unmapped surface has no parent, its children's parent is unset. If the now-unmapped surface becomes mapped again, its parent-child relationship is not restored. The parent toplevel must not be one of the child toplevel's descendants, and the parent must be different from the child toplevel, otherwise the invalid_parent protocol error is raised.
  xdg_toplevel_set_parent(obj.handle, Parent.handle)

proc `title=`*(obj: Toplevel, Title: cstring) =
  ## =====
  ## set surface title
  ## =====
  ## Set a short title for the surface. This string may be used to identify the surface in a task bar, window list, or other user interface elements provided by the compositor. The string must be encoded in UTF-8.
  xdg_toplevel_set_title(obj.handle, Title)

proc `appId=`*(obj: Toplevel, AppId: cstring) =
  ## =====
  ## set application ID
  ## =====
  ## Set an application identifier for the surface. The app ID identifies the general class of applications to which the surface belongs. The compositor can use this to group multiple surfaces together, or to determine how to launch a new application. For D-Bus activatable applications, the app ID is used as the D-Bus service name. The compositor shell will try to group application surfaces together by their app ID. As a best practice, it is suggested to select app ID's that match the basename of the application's .desktop file. For example, "org.freedesktop.FooViewer" where the .desktop file is "org.freedesktop.FooViewer.desktop". Like other properties, a set_app_id request can be sent after the xdg_toplevel has been mapped to update the property. See the desktop-entry specification [0] for more details on application identifiers and how they relate to well-known D-Bus names and .desktop files. [0] https://standards.freedesktop.org/desktop-entry-spec/
  xdg_toplevel_set_app_id(obj.handle, AppId)

proc showWindowMenu*(obj: Toplevel, Seat: Seat, Serial: uint32, X: int32, Y: int32) =
  ## =====
  ## show the window menu
  ## =====
  ## Clients implementing client-side decorations might want to show a context menu when right-clicking on the decorations, giving the user a menu that they can use to maximize or minimize the window. This request asks the compositor to pop up such a window menu at the given position, relative to the local surface coordinates of the parent surface. There are no guarantees as to what menu items the window menu contains, or even if a window menu will be drawn at all. This request must be used in response to some sort of user action like a button press, key press, or touch down event.
  xdg_toplevel_show_window_menu(obj.handle, Seat.handle, Serial, X, Y)

proc move*(obj: Toplevel, Seat: Seat, Serial: uint32) =
  ## =====
  ## start an interactive move
  ## =====
  ## Start an interactive, user-driven move of the surface. This request must be used in response to some sort of user action like a button press, key press, or touch down event. The passed serial is used to determine the type of interactive move (touch, pointer, etc). The server may ignore move requests depending on the state of the surface (e.g. fullscreen or maximized), or if the passed serial is no longer valid. If triggered, the surface will lose the focus of the device (wl_pointer, wl_touch, etc) used for the move. It is up to the compositor to visually indicate that the move is taking place, such as updating a pointer cursor, during the move. There is no guarantee that the device focus will return when the move is completed.
  xdg_toplevel_move(obj.handle, Seat.handle, Serial)

proc resize*(obj: Toplevel, Seat: Seat, Serial: uint32, Edges: uint32) =
  ## =====
  ## start an interactive resize
  ## =====
  ## Start a user-driven, interactive resize of the surface. This request must be used in response to some sort of user action like a button press, key press, or touch down event. The passed serial is used to determine the type of interactive resize (touch, pointer, etc). The server may ignore resize requests depending on the state of the surface (e.g. fullscreen or maximized). If triggered, the client will receive configure events with the "resize" state enum value and the expected sizes. See the "resize" enum value for more details about what is required. The client must also acknowledge configure events using "ack_configure". After the resize is completed, the client will receive another "configure" event without the resize state. If triggered, the surface also will lose the focus of the device (wl_pointer, wl_touch, etc) used for the resize. It is up to the compositor to visually indicate that the resize is taking place, such as updating a pointer cursor, during the resize. There is no guarantee that the device focus will return when the resize is completed. The edges parameter specifies how the surface should be resized, and is one of the values of the resize_edge enum. Values not matching a variant of the enum will cause the invalid_resize_edge protocol error. The compositor may use this information to update the surface position for example when dragging the top left corner. The compositor may also use this information to adapt its behavior, e.g. choose an appropriate cursor image.
  xdg_toplevel_resize(obj.handle, Seat.handle, Serial, Edges)

proc setMaxSize*(obj: Toplevel, Width: int32, Height: int32) =
  ## =====
  ## set the maximum size
  ## =====
  ## Set a maximum size for the window. The client can specify a maximum size so that the compositor does not try to configure the window beyond this size. The width and height arguments are in window geometry coordinates. See xdg_surface.set_window_geometry. Values set in this way are double-buffered, see wl_surface.commit. The compositor can use this information to allow or disallow different states like maximize or fullscreen and draw accurate animations. Similarly, a tiling window manager may use this information to place and resize client windows in a more effective way. The client should not rely on the compositor to obey the maximum size. The compositor may decide to ignore the values set by the client and request a larger size. If never set, or a value of zero in the request, means that the client has no expected maximum size in the given dimension. As a result, a client wishing to reset the maximum size to an unspecified state can use zero for width and height in the request. Requesting a maximum size to be smaller than the minimum size of a surface is illegal and will result in an invalid_size error. The width and height must be greater than or equal to zero. Using strictly negative values for width or height will result in a invalid_size error.
  xdg_toplevel_set_max_size(obj.handle, Width, Height)

proc setMinSize*(obj: Toplevel, Width: int32, Height: int32) =
  ## =====
  ## set the minimum size
  ## =====
  ## Set a minimum size for the window. The client can specify a minimum size so that the compositor does not try to configure the window below this size. The width and height arguments are in window geometry coordinates. See xdg_surface.set_window_geometry. Values set in this way are double-buffered, see wl_surface.commit. The compositor can use this information to allow or disallow different states like maximize or fullscreen and draw accurate animations. Similarly, a tiling window manager may use this information to place and resize client windows in a more effective way. The client should not rely on the compositor to obey the minimum size. The compositor may decide to ignore the values set by the client and request a smaller size. If never set, or a value of zero in the request, means that the client has no expected minimum size in the given dimension. As a result, a client wishing to reset the minimum size to an unspecified state can use zero for width and height in the request. Requesting a minimum size to be larger than the maximum size of a surface is illegal and will result in an invalid_size error. The width and height must be greater than or equal to zero. Using strictly negative values for width and height will result in a invalid_size error.
  xdg_toplevel_set_min_size(obj.handle, Width, Height)

proc setMaximized*(obj: Toplevel) =
  ## =====
  ## maximize the window
  ## =====
  ## Maximize the surface. After requesting that the surface should be maximized, the compositor will respond by emitting a configure event. Whether this configure actually sets the window maximized is subject to compositor policies. The client must then update its content, drawing in the configured state. The client must also acknowledge the configure when committing the new content (see ack_configure). It is up to the compositor to decide how and where to maximize the surface, for example which output and what region of the screen should be used. If the surface was already maximized, the compositor will still emit a configure event with the "maximized" state. If the surface is in a fullscreen state, this request has no direct effect. It may alter the state the surface is returned to when unmaximized unless overridden by the compositor.
  xdg_toplevel_set_maximized(obj.handle)

proc unsetMaximized*(obj: Toplevel) =
  ## =====
  ## unmaximize the window
  ## =====
  ## Unmaximize the surface. After requesting that the surface should be unmaximized, the compositor will respond by emitting a configure event. Whether this actually un-maximizes the window is subject to compositor policies. If available and applicable, the compositor will include the window geometry dimensions the window had prior to being maximized in the configure event. The client must then update its content, drawing it in the configured state. The client must also acknowledge the configure when committing the new content (see ack_configure). It is up to the compositor to position the surface after it was unmaximized; usually the position the surface had before maximizing, if applicable. If the surface was already not maximized, the compositor will still emit a configure event without the "maximized" state. If the surface is in a fullscreen state, this request has no direct effect. It may alter the state the surface is returned to when unmaximized unless overridden by the compositor.
  xdg_toplevel_unset_maximized(obj.handle)

proc setFullscreen*(obj: Toplevel, Output: Output) =
  ## =====
  ## set the window as fullscreen on an output
  ## =====
  ## Make the surface fullscreen. After requesting that the surface should be fullscreened, the compositor will respond by emitting a configure event. Whether the client is actually put into a fullscreen state is subject to compositor policies. The client must also acknowledge the configure when committing the new content (see ack_configure). The output passed by the request indicates the client's preference as to which display it should be set fullscreen on. If this value is NULL, it's up to the compositor to choose which display will be used to map this surface. If the surface doesn't cover the whole output, the compositor will position the surface in the center of the output and compensate with with border fill covering the rest of the output. The content of the border fill is undefined, but should be assumed to be in some way that attempts to blend into the surrounding area (e.g. solid black). If the fullscreened surface is not opaque, the compositor must make sure that other screen content not part of the same surface tree (made up of subsurfaces, popups or similarly coupled surfaces) are not visible below the fullscreened surface.
  xdg_toplevel_set_fullscreen(obj.handle, Output.handle)

proc unsetFullscreen*(obj: Toplevel) =
  ## =====
  ## unset the window as fullscreen
  ## =====
  ## Make the surface no longer fullscreen. After requesting that the surface should be unfullscreened, the compositor will respond by emitting a configure event. Whether this actually removes the fullscreen state of the client is subject to compositor policies. Making a surface unfullscreen sets states for the surface based on the following: * the state(s) it may have had before becoming fullscreen * any state(s) decided by the compositor * any state(s) requested by the client while the surface was fullscreen The compositor may include the previous window geometry dimensions in the configure event, if applicable. The client must also acknowledge the configure when committing the new content (see ack_configure).
  xdg_toplevel_unset_fullscreen(obj.handle)

proc setMinimized*(obj: Toplevel) =
  ## =====
  ## set the window as minimized
  ## =====
  ## Request that the compositor minimize your surface. There is no way to know if the surface is currently minimized, nor is there any way to unset minimization on this surface. If you are looking to throttle redrawing when minimized, please instead use the wl_surface.frame event for this, as this will also work with live previews on windows in Alt-Tab, Expose or similar compositor features.
  xdg_toplevel_set_minimized(obj.handle)

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Error): uint32 =
  cast[uint32](v)

converter shim1*(v: Resize_edge): uint32 =
  cast[uint32](v)

converter shim2*(v: State): uint32 =
  cast[uint32](v)

converter shim3*(v: Wm_capabilities): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
