## Wrapper around `wp_cursor_shape_device_v1` (`CursorShapeDevice`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, cursor_shape_v1]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Shape* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## cursor shapes
    ## =====
    ## This enum describes cursor shapes. The names are taken from the CSS W3C specification: https://w3c.github.io/csswg-drafts/css-ui/#cursor with a few additions. Note that there are some groups of cursor shapes that are related: The first group is drag-and-drop cursors which are used to indicate the selected action during dnd operations. The second group is resize cursors which are used to indicate resizing and moving possibilities on window borders. It is recommended that the shapes in these groups should use visually compatible images and metaphors.
    Default = 1'u32 ## default cursor
    ContextMenu = 2'u32 ## a context menu is available for the object under the cursor
    Help = 3'u32 ## help is available for the object under the cursor
    Pointer = 4'u32 ## pointer that indicates a link or another interactive element
    Progress = 5'u32 ## progress indicator
    Wait = 6'u32 ## program is busy, user should wait
    Cell = 7'u32 ## a cell or set of cells may be selected
    Crosshair = 8'u32 ## simple crosshair
    Text = 9'u32 ## text may be selected
    VerticalText = 10'u32 ## vertical text may be selected
    Alias = 11'u32 ## drag-and-drop: alias of/shortcut to something is to be created
    Copy = 12'u32 ## drag-and-drop: something is to be copied
    Move = 13'u32 ## drag-and-drop: something is to be moved
    NoDrop = 14'u32 ## drag-and-drop: the dragged item cannot be dropped at the current cursor location
    NotAllowed = 15'u32 ## drag-and-drop: the requested action will not be carried out
    Grab = 16'u32 ## drag-and-drop: something can be grabbed
    Grabbing = 17'u32 ## drag-and-drop: something is being grabbed
    EResize = 18'u32 ## resizing: the east border is to be moved
    NResize = 19'u32 ## resizing: the north border is to be moved
    NeResize = 20'u32 ## resizing: the north-east corner is to be moved
    NwResize = 21'u32 ## resizing: the north-west corner is to be moved
    SResize = 22'u32 ## resizing: the south border is to be moved
    SeResize = 23'u32 ## resizing: the south-east corner is to be moved
    SwResize = 24'u32 ## resizing: the south-west corner is to be moved
    WResize = 25'u32 ## resizing: the west border is to be moved
    EwResize = 26'u32 ## resizing: the east and west borders are to be moved
    NsResize = 27'u32 ## resizing: the north and south borders are to be moved
    NeswResize = 28'u32 ## resizing: the north-east and south-west corners are to be moved
    NwseResize = 29'u32 ## resizing: the north-west and south-east corners are to be moved
    ColResize = 30'u32 ## resizing: that the item/column can be resized horizontally
    RowResize = 31'u32 ## resizing: that the item/row can be resized vertically
    AllScroll = 32'u32 ## something can be scrolled in any direction
    ZoomIn = 33'u32 ## something can be zoomed in
    ZoomOut = 34'u32 ## something can be zoomed out
    DndAsk = 35'u32 ## drag-and-drop: the user will select which action will be carried out (non-css value)
    AllResize = 36'u32 ## resizing: something can be moved or resized in any direction (non-css value)

  Error* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    InvalidShape = 1'u32 ## the specified shape value is invalid

  CursorShapeDeviceObj* = object
    handle*: ptr wp_cursor_shape_device_v1

  CursorShapeDevice* = ref CursorShapeDeviceObj
    ## =====
    ## cursor shape for a device
    ## =====
    ## This interface allows clients to set the cursor shape.

# wrapgen: end emitting interface structures
# wrapgen: start emitting request wrappers
proc `=destroy`*(obj: CursorShapeDeviceObj) =
  ## =====
  ## destroy the cursor shape device
  ## =====
  ## Destroy the cursor shape device. The device cursor shape remains unchanged.
  wp_cursor_shape_device_v1_destroy(obj.handle)


proc setShape*(obj: CursorShapeDevice, Serial: uint32, Shape: uint32) =
  ## =====
  ## set device cursor to the shape
  ## =====
  ## Sets the device cursor to the specified shape. The compositor will change the cursor image based on the specified shape. The cursor actually changes only if the input device focus is one of the requesting client's surfaces. If any, the previous cursor image (surface or shape) is replaced. The "shape" argument must be a valid enum entry, otherwise the invalid_shape protocol error is raised. This is similar to the wl_pointer.set_cursor and zwp_tablet_tool_v2.set_cursor requests, but this request accepts a shape instead of contents in the form of a surface. Clients can mix set_cursor and set_shape requests. The serial parameter must match the latest wl_pointer.enter or zwp_tablet_tool_v2.proximity_in serial number sent to the client. Otherwise the request will be ignored.
  wp_cursor_shape_device_v1_set_shape(obj.handle, Serial, Shape)

# wrapgen: end emitting request wrappers
# wrapgen: begin emitting constructor routines
func initCursorShapeDevice*(raw: ptr wp_cursor_shape_device_v1 | pointer): CursorShapeDevice =
  ## Instantiate a CursorShapeDevice using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initCursorShapeDevice() was given an uninitialized handle!")
  
  CursorShapeDevice(handle: cast[ptr wp_cursor_shape_device_v1](raw))

func newCursorShapeDevice*(raw: ptr wp_cursor_shape_device_v1): CursorShapeDevice =
  ## Instantiate a CursorShapeDevice using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newCursorShapeDevice() was given an uninitialized handle!")
  
  CursorShapeDevice(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting enum shims
converter shim0*(v: Shape): uint32 = cast[uint32](v)
converter shim1*(v: Error): uint32 = cast[uint32](v)
# wrapgen: end emitting enum shims
