## Wrapper around `wp_cursor_shape_manager_v1` (`CursorShapeManager`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, cursor_shape_v1]
import
  pkg/nayland/types/protocols/core/prelude,
  pkg/nayland/types/protocols/cursor_shape/device
# wrapgen: begin emitting interface structures
type
  CursorShapeManagerObj* = object
    handle*: ptr wp_cursor_shape_manager_v1

  CursorShapeManager* = ref CursorShapeManagerObj
    ## =====
    ## cursor shape manager
    ## =====
    ## This global offers an alternative, optional way to set cursor images. This new way uses enumerated cursors instead of a wl_surface like wl_pointer.set_cursor does. Warning! The protocol described in this file is currently in the testing phase. Backward compatible changes may be added together with the corresponding interface version bump. Backward incompatible changes can only be done by creating a new major version of the extension.

# wrapgen: end emitting interface structures
# wrapgen: start emitting request wrappers
proc `=destroy`*(obj: CursorShapeManagerObj) =
  ## =====
  ## destroy the manager
  ## =====
  ## Destroy the cursor shape manager.
  wp_cursor_shape_manager_v1_destroy(obj.handle)

proc getPointer*(obj: CursorShapeManager, Pointer: Pointer): CursorShapeDevice =
  ## =====
  ## manage the cursor shape of a pointer device
  ## =====
  ## Obtain a wp_cursor_shape_device_v1 for a wl_pointer object. When the pointer capability is removed from the wl_seat, the wp_cursor_shape_device_v1 object becomes inert.
  initCursorShapeDevice(
    wp_cursor_shape_manager_v1_get_pointer(obj.handle, Pointer.handle)
  )

# wrapgen: end emitting request wrappers
# wrapgen: begin emitting constructor routines
func initCursorShapeManager*(
    raw: ptr wp_cursor_shape_manager_v1 | pointer
): CursorShapeManager =
  ## Instantiate a CursorShapeManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initCursorShapeManager() was given an uninitialized handle!"
    )

  CursorShapeManager(handle: cast[ptr wp_cursor_shape_manager_v1](raw))

func newCursorShapeManager*(raw: ptr wp_cursor_shape_manager_v1): CursorShapeManager =
  ## Instantiate a CursorShapeManager using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: newCursorShapeManager() was given an uninitialized handle!"
    )

  CursorShapeManager(handle: raw)

# wrapgen: end emitting constructor routines
