## Wrapper around `zwp_linux_dmabuf_feedback_v1` (`LinuxDmabufFeedback`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import std/posix
import pkg/nayland/bindings/protocols/[core, linux_dmabuf_v1]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  Tranche_flags* {.pure, size: sizeof(uint32).} = enum
    ## =====
    ## 
    ## =====
    ## 
    Scanout = 1'u32 ## direct scan-out tranche

  LinuxDmabufFeedbackObj* = object
    handle*: ptr zwp_linux_dmabuf_feedback_v1
    payload: LinuxDmabufFeedbackPayload

  LinuxDmabufFeedbackPayload = ref object
    doneCb: LinuxDmabufFeedbackDoneCallback
    format_tableCb: LinuxDmabufFeedbackFormatTableCallback
    main_deviceCb: LinuxDmabufFeedbackMainDeviceCallback
    tranche_doneCb: LinuxDmabufFeedbackTrancheDoneCallback
    tranche_target_deviceCb: LinuxDmabufFeedbackTrancheTargetDeviceCallback
    tranche_formatsCb: LinuxDmabufFeedbackTrancheFormatsCallback
    tranche_flagsCb: LinuxDmabufFeedbackTrancheFlagsCallback

  LinuxDmabufFeedback* = ref LinuxDmabufFeedbackObj
    ## =====
    ## dmabuf feedback
    ## =====
    ## This object advertises dmabuf parameters feedback. This includes the preferred devices and the supported formats/modifiers. The parameters are sent once when this object is created and whenever they change. The done event is always sent once after all parameters have been sent. When a single parameter changes, all parameters are re-sent by the compositor. Compositors can re-send the parameters when the current client buffer allocations are sub-optimal. Compositors should not re-send the parameters if re-allocating the buffers would not result in a more optimal configuration. In particular, compositors should avoid sending the exact same parameters multiple times in a row. The tranche_target_device and tranche_formats events are grouped by tranches of preference. For each tranche, a tranche_target_device, one tranche_flags and one or more tranche_formats events are sent, followed by a tranche_done event finishing the list. The tranches are sent in descending order of preference. All formats and modifiers in the same tranche have the same preference. To send parameters, the compositor sends one main_device event, tranches (each consisting of one tranche_target_device event, one tranche_flags event, tranche_formats events and then a tranche_done event), then one done event.

  LinuxDmabufFeedbackDoneCallback* = proc()
  LinuxDmabufFeedbackFormatTableCallback* = proc(fd: int32, size: uint32)
  LinuxDmabufFeedbackMainDeviceCallback* = proc(device: seq[posix.Dev])
  LinuxDmabufFeedbackTrancheDoneCallback* = proc()
  LinuxDmabufFeedbackTrancheTargetDeviceCallback* = proc(device: seq[posix.Dev])
  LinuxDmabufFeedbackTrancheFormatsCallback* = proc(indices: seq[uint16])
  LinuxDmabufFeedbackTrancheFlagsCallback* = proc(flags: uint32)

proc `=destroy`*(obj: LinuxDmabufFeedbackObj) =
  ## =====
  ## destroy the feedback object
  ## =====
  ## Using this request a client can tell the server that it is not going to use the zwp_linux_dmabuf_feedback_v1 object anymore.
  zwp_linux_dmabuf_feedback_v1_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initLinuxDmabufFeedback*(
    raw: ptr zwp_linux_dmabuf_feedback_v1 | pointer
): LinuxDmabufFeedback =
  ## Instantiate a LinuxDmabufFeedback using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initLinuxDmabufFeedback() was given an uninitialized handle!"
    )

  LinuxDmabufFeedback(
    handle: cast[ptr zwp_linux_dmabuf_feedback_v1](raw),
    payload: LinuxDmabufFeedbackPayload(),
  )

func newLinuxDmabufFeedback*(
    raw: ptr zwp_linux_dmabuf_feedback_v1
): LinuxDmabufFeedback =
  ## Instantiate a LinuxDmabufFeedback using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: newLinuxDmabufFeedback() was given an uninitialized handle!"
    )

  LinuxDmabufFeedback(handle: raw, payload: LinuxDmabufFeedbackPayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = zwp_linux_dmabuf_feedback_v1_listener(
  done: proc(data: pointer, this: ptr zwp_linux_dmabuf_feedback_v1) {.cdecl.} =
    let payload = cast[LinuxDmabufFeedbackPayload](data)
    if payload.doneCb == nil:
      write(stderr, "[nayland] handler not attached for event 'done'!\n")
      return

    payload.doneCb(),
  format_table: proc(
      data: pointer, this: ptr zwp_linux_dmabuf_feedback_v1, fd: int32, size: uint32
  ) {.cdecl.} =
    let payload = cast[LinuxDmabufFeedbackPayload](data)
    if payload.format_tableCb == nil:
      write(stderr, "[nayland] handler not attached for event 'format_table'!\n")
      return

    payload.format_tableCb(fd, size),
  main_device: proc(
      data: pointer, this: ptr zwp_linux_dmabuf_feedback_v1, device: ptr wl_array
  ) {.cdecl.} =
    let payload = cast[LinuxDmabufFeedbackPayload](data)
    if payload.main_deviceCb == nil:
      write(stderr, "[nayland] handler not attached for event 'main_device'!\n")
      return

    var deviceVec = newSeq[posix.Dev](device.size)
    for i in 0 ..< device.size:
      deviceVec[i] = cast[ptr UncheckedArray[posix.Dev]](device.data)[i]

    payload.main_deviceCb(ensureMove(deviceVec)),
  tranche_done: proc(data: pointer, this: ptr zwp_linux_dmabuf_feedback_v1) {.cdecl.} =
    let payload = cast[LinuxDmabufFeedbackPayload](data)
    if payload.tranche_doneCb == nil:
      write(stderr, "[nayland] handler not attached for event 'tranche_done'!\n")
      return

    payload.tranche_doneCb(),
  tranche_target_device: proc(
      data: pointer, this: ptr zwp_linux_dmabuf_feedback_v1, device: ptr wl_array
  ) {.cdecl.} =
    let payload = cast[LinuxDmabufFeedbackPayload](data)
    if payload.tranche_target_deviceCb == nil:
      write(
        stderr, "[nayland] handler not attached for event 'tranche_target_device'!\n"
      )
      return

    var deviceVec = newSeq[posix.Dev](device.size)
    for i in 0 ..< device.size:
      deviceVec[i] = cast[ptr UncheckedArray[posix.Dev]](device.data)[i]

    payload.tranche_target_deviceCb(ensureMove(deviceVec)),
  tranche_formats: proc(
      data: pointer, this: ptr zwp_linux_dmabuf_feedback_v1, indices: ptr wl_array
  ) {.cdecl.} =
    let payload = cast[LinuxDmabufFeedbackPayload](data)
    if payload.tranche_formatsCb == nil:
      write(stderr, "[nayland] handler not attached for event 'tranche_formats'!\n")
      return

    var indicesVec = newSeq[uint16](indices.size)
    for i in 0 ..< indices.size:
      indicesVec[i] = cast[ptr UncheckedArray[uint16]](indices.data)[i]

    payload.tranche_formatsCb(ensureMove(indicesVec)),
  tranche_flags: proc(
      data: pointer, this: ptr zwp_linux_dmabuf_feedback_v1, flags: uint32
  ) {.cdecl.} =
    let payload = cast[LinuxDmabufFeedbackPayload](data)
    if payload.tranche_flagsCb == nil:
      write(stderr, "[nayland] handler not attached for event 'tranche_flags'!\n")
      return

    payload.tranche_flagsCb(flags),
)
proc attachCallbacks*(obj: LinuxDmabufFeedback) =
  discard zwp_linux_dmabuf_feedback_v1_add_listener(
    obj.handle, listener.addr, cast[pointer](obj.payload)
  )

func `onDone=`*(
    obj: LinuxDmabufFeedback, cb: LinuxDmabufFeedbackDoneCallback
) {.inline, raises: [].} =
  obj.payload.doneCb = cb
func `onFormatTable=`*(
    obj: LinuxDmabufFeedback, cb: LinuxDmabufFeedbackFormatTableCallback
) {.inline, raises: [].} =
  obj.payload.format_tableCb = cb
func `onMainDevice=`*(
    obj: LinuxDmabufFeedback, cb: LinuxDmabufFeedbackMainDeviceCallback
) {.inline, raises: [].} =
  obj.payload.main_deviceCb = cb
func `onTrancheDone=`*(
    obj: LinuxDmabufFeedback, cb: LinuxDmabufFeedbackTrancheDoneCallback
) {.inline, raises: [].} =
  obj.payload.tranche_doneCb = cb
func `onTrancheTargetDevice=`*(
    obj: LinuxDmabufFeedback, cb: LinuxDmabufFeedbackTrancheTargetDeviceCallback
) {.inline, raises: [].} =
  obj.payload.tranche_target_deviceCb = cb
func `onTrancheFormats=`*(
    obj: LinuxDmabufFeedback, cb: LinuxDmabufFeedbackTrancheFormatsCallback
) {.inline, raises: [].} =
  obj.payload.tranche_formatsCb = cb
func `onTrancheFlags=`*(
    obj: LinuxDmabufFeedback, cb: LinuxDmabufFeedbackTrancheFlagsCallback
) {.inline, raises: [].} =
  obj.payload.tranche_flagsCb = cb

# wrapgen: start emitting request wrappers

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
converter shim0*(v: Tranche_flags): uint32 =
  cast[uint32](v)

# wrapgen: end emitting enum shims
