## Wrapper around `zwp_pointer_gestures_v1` (`PointerGestures`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, pointer_gestures_unstable_v1]
import
  pkg/nayland/types/protocols/core/prelude,
  pkg/nayland/types/protocols/pointer_gestures_unstable/[hold, pinch, swipe]
# wrapgen: begin emitting interface structures
type
  PointerGesturesObj* = object
    handle*: ptr zwp_pointer_gestures_v1

  PointerGestures* = ref PointerGesturesObj
    ## =====
    ## touchpad gestures
    ## =====
    ## A global interface to provide semantic touchpad gestures for a given pointer. Three gestures are currently supported: swipe, pinch, and hold. Pinch and swipe gestures follow a three-stage cycle: begin, update, end. Hold gestures follow a two-stage cycle: begin and end. All gestures are identified by a unique id. Warning! The protocol described in this file is experimental and backward incompatible changes may be made. Backward compatible changes may be added together with the corresponding interface version bump. Backward incompatible changes are done by bumping the version number in the protocol and interface names and resetting the interface version. Once the protocol is to be declared stable, the 'z' prefix and the version number in the protocol and interface names are removed and the interface version number is reset.

proc `=destroy`*(obj: PointerGesturesObj) =
  ## =====
  ## destroy the pointer gesture object
  ## =====
  ## Destroy the pointer gesture object. Swipe, pinch and hold objects created via this gesture object remain valid.
  zwp_pointer_gestures_v1_release(obj.handle)

# wrapgen: begin emitting constructor routines
func initPointerGestures*(raw: ptr zwp_pointer_gestures_v1 | pointer): PointerGestures =
  ## Instantiate a PointerGestures using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: initPointerGestures() was given an uninitialized handle!")

  PointerGestures(handle: cast[ptr zwp_pointer_gestures_v1](raw))

func newPointerGestures*(raw: ptr zwp_pointer_gestures_v1): PointerGestures =
  ## Instantiate a PointerGestures using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(raw != nil, "BUG: newPointerGestures() was given an uninitialized handle!")

  PointerGestures(handle: raw)

# wrapgen: end emitting constructor routines

# wrapgen: start emitting request wrappers

proc getSwipeGesture*(obj: PointerGestures, Pointer: Pointer): PointerGestureSwipe =
  ## =====
  ## get swipe gesture
  ## =====
  ## Create a swipe gesture object. See the wl_pointer_gesture_swipe interface for details.
  initPointerGestureSwipe(
    zwp_pointer_gestures_v1_get_swipe_gesture(obj.handle, Pointer.handle)
  )

proc getPinchGesture*(obj: PointerGestures, Pointer: Pointer): PointerGesturePinch =
  ## =====
  ## get pinch gesture
  ## =====
  ## Create a pinch gesture object. See the wl_pointer_gesture_pinch interface for details.
  initPointerGesturePinch(
    zwp_pointer_gestures_v1_get_pinch_gesture(obj.handle, Pointer.handle)
  )

proc getHoldGesture*(obj: PointerGestures, Pointer: Pointer): PointerGestureHold =
  ## =====
  ## get hold gesture
  ## =====
  ## Create a hold gesture object. See the wl_pointer_gesture_hold interface for details.
  initPointerGestureHold(
    zwp_pointer_gestures_v1_get_hold_gesture(obj.handle, Pointer.handle)
  )

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
