## Wrapper around `zwp_pointer_gesture_hold_v1` (`PointerGestureHold`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, pointer_gestures_unstable_v1]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  PointerGestureHoldObj* = object
    handle*: ptr zwp_pointer_gesture_hold_v1
    payload: PointerGestureHoldPayload

  PointerGestureHold* = ref PointerGestureHoldObj
    ## =====
    ## a hold gesture object
    ## =====
    ## A hold gesture object notifies a client about a single- or multi-finger hold gesture detected on an indirect input device such as a touchpad. The gesture is usually initiated by one or more fingers being held down without significant movement. The precise conditions of when such a gesture is detected are implementation-dependent. In particular, this gesture may be used to cancel kinetic scrolling. A hold gesture consists of two stages: begin and end. Unlike pinch and swipe there is no update stage. There cannot be multiple simultaneous hold, pinch or swipe gestures on a same pointer/seat, how compositors prevent these situations is implementation-dependent. A gesture may be cancelled by the compositor or the hardware. Clients should not consider performing permanent or irreversible actions until the end of a gesture has been received.

  PointerGestureHoldBeginCallback* =
    proc(serial: uint32, time: uint32, surface: Surface, fingers: uint32)
  PointerGestureHoldEndCallback* = proc(serial: uint32, time: uint32, cancelled: int32)
  PointerGestureHoldPayload = ref object
    beginCb: PointerGestureHoldBeginCallback
    endCb: PointerGestureHoldEndCallback

proc `=destroy`*(obj: PointerGestureHoldObj) =
  ## =====
  ## destroy the hold gesture object
  ## =====
  ## 
  zwp_pointer_gesture_hold_v1_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initPointerGestureHold*(
    raw: ptr zwp_pointer_gesture_hold_v1 | pointer
): PointerGestureHold =
  ## Instantiate a PointerGestureHold using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initPointerGestureHold() was given an uninitialized handle!"
    )

  PointerGestureHold(
    handle: cast[ptr zwp_pointer_gesture_hold_v1](raw),
    payload: PointerGestureHoldPayload(),
  )

func newPointerGestureHold*(raw: ptr zwp_pointer_gesture_hold_v1): PointerGestureHold =
  ## Instantiate a PointerGestureHold using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: newPointerGestureHold() was given an uninitialized handle!"
    )

  PointerGestureHold(handle: raw, payload: PointerGestureHoldPayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = zwp_pointer_gesture_hold_v1_listener(
  begin: proc(
      data: pointer,
      this: ptr zwp_pointer_gesture_hold_v1,
      serial: uint32,
      time: uint32,
      surface: ptr wl_surface,
      fingers: uint32,
  ) {.cdecl.} =
    let payload = cast[PointerGestureHoldPayload](data)
    if payload.beginCb == nil:
      write(stderr, "[nayland] handler not attached for event 'begin'!\n")
      return

    payload.beginCb(serial, time, surface.newSurface(), fingers),
  `end`: proc(
      data: pointer,
      this: ptr zwp_pointer_gesture_hold_v1,
      serial: uint32,
      time: uint32,
      cancelled: int32,
  ) {.cdecl.} =
    let payload = cast[PointerGestureHoldPayload](data)
    if payload.endCb == nil:
      write(stderr, "[nayland] handler not attached for event 'end'!\n")
      return

    payload.endCb(serial, time, cancelled),
)
proc attachCallbacks*(obj: PointerGestureHold) =
  discard zwp_pointer_gesture_hold_v1_add_listener(
    obj.handle, listener.addr, cast[pointer](obj.payload)
  )

func `onBegin=`*(
    obj: PointerGestureHold, cb: PointerGestureHoldBeginCallback
) {.inline, raises: [].} =
  obj.payload.beginCb = cb
func `onEnd=`*(
    obj: PointerGestureHold, cb: PointerGestureHoldEndCallback
) {.inline, raises: [].} =
  obj.payload.endCb = cb

# wrapgen: start emitting request wrappers

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
