## Wrapper around `zwp_pointer_gesture_pinch_v1` (`PointerGesturePinch`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, pointer_gestures_unstable_v1]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  PointerGesturePinchObj* = object
    handle*: ptr zwp_pointer_gesture_pinch_v1
    payload: PointerGesturePinchPayload

  PointerGesturePinch* = ref PointerGesturePinchObj
    ## =====
    ## a pinch gesture object
    ## =====
    ## A pinch gesture object notifies a client about a multi-finger pinch gesture detected on an indirect input device such as a touchpad. The gesture is usually initiated by multiple fingers moving towards each other or away from each other, or by two or more fingers rotating around a logical center of gravity. The precise conditions of when such a gesture is detected are implementation-dependent. A gesture consists of three stages: begin, update (optional) and end. There cannot be multiple simultaneous hold, pinch or swipe gestures on a same pointer/seat, how compositors prevent these situations is implementation-dependent. A gesture may be cancelled by the compositor or the hardware. Clients should not consider performing permanent or irreversible actions until the end of a gesture has been received.

  PointerGesturePinchBeginCallback* =
    proc(serial: uint32, time: uint32, surface: Surface, fingers: uint32)
  PointerGesturePinchUpdateCallback* =
    proc(time: uint32, dx: float, dy: float, scale: float, rotation: float)
  PointerGesturePinchEndCallback* = proc(serial: uint32, time: uint32, cancelled: int32)
  PointerGesturePinchPayload = ref object
    beginCb: PointerGesturePinchBeginCallback
    updateCb: PointerGesturePinchUpdateCallback
    endCb: PointerGesturePinchEndCallback

proc `=destroy`*(obj: PointerGesturePinchObj) =
  ## =====
  ## destroy the pinch gesture object
  ## =====
  ## 
  zwp_pointer_gesture_pinch_v1_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initPointerGesturePinch*(
    raw: ptr zwp_pointer_gesture_pinch_v1 | pointer
): PointerGesturePinch =
  ## Instantiate a PointerGesturePinch using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initPointerGesturePinch() was given an uninitialized handle!"
    )

  PointerGesturePinch(
    handle: cast[ptr zwp_pointer_gesture_pinch_v1](raw),
    payload: PointerGesturePinchPayload(),
  )

func newPointerGesturePinch*(
    raw: ptr zwp_pointer_gesture_pinch_v1
): PointerGesturePinch =
  ## Instantiate a PointerGesturePinch using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: newPointerGesturePinch() was given an uninitialized handle!"
    )

  PointerGesturePinch(handle: raw, payload: PointerGesturePinchPayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = zwp_pointer_gesture_pinch_v1_listener(
  begin: proc(
      data: pointer,
      this: ptr zwp_pointer_gesture_pinch_v1,
      serial: uint32,
      time: uint32,
      surface: ptr wl_surface,
      fingers: uint32,
  ) {.cdecl.} =
    let payload = cast[PointerGesturePinchPayload](data)
    if payload.beginCb == nil:
      write(stderr, "[nayland] handler not attached for event 'begin'!\n")
      return

    payload.beginCb(serial, time, surface.newSurface(), fingers),
  update: proc(
      data: pointer,
      this: ptr zwp_pointer_gesture_pinch_v1,
      time: uint32,
      dx: wl_fixed,
      dy: wl_fixed,
      scale: wl_fixed,
      rotation: wl_fixed,
  ) {.cdecl.} =
    let payload = cast[PointerGesturePinchPayload](data)
    if payload.updateCb == nil:
      write(stderr, "[nayland] handler not attached for event 'update'!\n")
      return

    payload.updateCb(time, dx.toFloat, dy.toFloat, scale.toFloat, rotation.toFloat),
  `end`: proc(
      data: pointer,
      this: ptr zwp_pointer_gesture_pinch_v1,
      serial: uint32,
      time: uint32,
      cancelled: int32,
  ) {.cdecl.} =
    let payload = cast[PointerGesturePinchPayload](data)
    if payload.endCb == nil:
      write(stderr, "[nayland] handler not attached for event 'end'!\n")
      return

    payload.endCb(serial, time, cancelled),
)
proc attachCallbacks*(obj: PointerGesturePinch) =
  discard zwp_pointer_gesture_pinch_v1_add_listener(
    obj.handle, listener.addr, cast[pointer](obj.payload)
  )

func `onBegin=`*(
    obj: PointerGesturePinch, cb: PointerGesturePinchBeginCallback
) {.inline, raises: [].} =
  obj.payload.beginCb = cb
func `onUpdate=`*(
    obj: PointerGesturePinch, cb: PointerGesturePinchUpdateCallback
) {.inline, raises: [].} =
  obj.payload.updateCb = cb
func `onEnd=`*(
    obj: PointerGesturePinch, cb: PointerGesturePinchEndCallback
) {.inline, raises: [].} =
  obj.payload.endCb = cb

# wrapgen: start emitting request wrappers

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
