## Wrapper around `zwp_pointer_gesture_swipe_v1` (`PointerGestureSwipe`)
## Generated by wrapgen (protocols/wrapgen.nim).
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import pkg/nayland/bindings/protocols/[core, pointer_gestures_unstable_v1]
import pkg/nayland/types/protocols/core/prelude
# wrapgen: begin emitting interface structures
type
  PointerGestureSwipeObj* = object
    handle*: ptr zwp_pointer_gesture_swipe_v1
    payload: PointerGestureSwipePayload

  PointerGestureSwipe* = ref PointerGestureSwipeObj
    ## =====
    ## a swipe gesture object
    ## =====
    ## A swipe gesture object notifies a client about a multi-finger swipe gesture detected on an indirect input device such as a touchpad. The gesture is usually initiated by multiple fingers moving in the same direction but once initiated the direction may change. The precise conditions of when such a gesture is detected are implementation-dependent. A gesture consists of three stages: begin, update (optional) and end. There cannot be multiple simultaneous hold, pinch or swipe gestures on a same pointer/seat, how compositors prevent these situations is implementation-dependent. A gesture may be cancelled by the compositor or the hardware. Clients should not consider performing permanent or irreversible actions until the end of a gesture has been received.

  PointerGestureSwipeBeginCallback* =
    proc(serial: uint32, time: uint32, surface: Surface, fingers: uint32)
  PointerGestureSwipeUpdateCallback* = proc(time: uint32, dx: float, dy: float)
  PointerGestureSwipeEndCallback* = proc(serial: uint32, time: uint32, cancelled: int32)
  PointerGestureSwipePayload = ref object
    beginCb: PointerGestureSwipeBeginCallback
    updateCb: PointerGestureSwipeUpdateCallback
    endCb: PointerGestureSwipeEndCallback

proc `=destroy`*(obj: PointerGestureSwipeObj) =
  ## =====
  ## destroy the pointer swipe gesture object
  ## =====
  ## 
  zwp_pointer_gesture_swipe_v1_destroy(obj.handle)

# wrapgen: begin emitting constructor routines
func initPointerGestureSwipe*(
    raw: ptr zwp_pointer_gesture_swipe_v1 | pointer
): PointerGestureSwipe =
  ## Instantiate a PointerGestureSwipe using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: initPointerGestureSwipe() was given an uninitialized handle!"
    )

  PointerGestureSwipe(
    handle: cast[ptr zwp_pointer_gesture_swipe_v1](raw),
    payload: PointerGestureSwipePayload(),
  )

func newPointerGestureSwipe*(
    raw: ptr zwp_pointer_gesture_swipe_v1
): PointerGestureSwipe =
  ## Instantiate a PointerGestureSwipe using its low-level libwayland handle.
  ##
  ## **Note**: This routine does not accept NULL pointers (there is no reason to), and WILL crash upon being given one!
  when not defined(danger):
    assert(
      raw != nil, "BUG: newPointerGestureSwipe() was given an uninitialized handle!"
    )

  PointerGestureSwipe(handle: raw, payload: PointerGestureSwipePayload())

# wrapgen: end emitting constructor routines

let listener {.global.} = zwp_pointer_gesture_swipe_v1_listener(
  begin: proc(
      data: pointer,
      this: ptr zwp_pointer_gesture_swipe_v1,
      serial: uint32,
      time: uint32,
      surface: ptr wl_surface,
      fingers: uint32,
  ) {.cdecl.} =
    let payload = cast[PointerGestureSwipePayload](data)
    if payload.beginCb == nil:
      write(stderr, "[nayland] handler not attached for event 'begin'!\n")
      return

    payload.beginCb(serial, time, surface.newSurface(), fingers),
  update: proc(
      data: pointer,
      this: ptr zwp_pointer_gesture_swipe_v1,
      time: uint32,
      dx: wl_fixed,
      dy: wl_fixed,
  ) {.cdecl.} =
    let payload = cast[PointerGestureSwipePayload](data)
    if payload.updateCb == nil:
      write(stderr, "[nayland] handler not attached for event 'update'!\n")
      return

    payload.updateCb(time, dx.toFloat, dy.toFloat),
  `end`: proc(
      data: pointer,
      this: ptr zwp_pointer_gesture_swipe_v1,
      serial: uint32,
      time: uint32,
      cancelled: int32,
  ) {.cdecl.} =
    let payload = cast[PointerGestureSwipePayload](data)
    if payload.endCb == nil:
      write(stderr, "[nayland] handler not attached for event 'end'!\n")
      return

    payload.endCb(serial, time, cancelled),
)
proc attachCallbacks*(obj: PointerGestureSwipe) =
  discard zwp_pointer_gesture_swipe_v1_add_listener(
    obj.handle, listener.addr, cast[pointer](obj.payload)
  )

func `onBegin=`*(
    obj: PointerGestureSwipe, cb: PointerGestureSwipeBeginCallback
) {.inline, raises: [].} =
  obj.payload.beginCb = cb
func `onUpdate=`*(
    obj: PointerGestureSwipe, cb: PointerGestureSwipeUpdateCallback
) {.inline, raises: [].} =
  obj.payload.updateCb = cb
func `onEnd=`*(
    obj: PointerGestureSwipe, cb: PointerGestureSwipeEndCallback
) {.inline, raises: [].} =
  obj.payload.endCb = cb

# wrapgen: start emitting request wrappers

# wrapgen: end emitting request wrappers
# wrapgen: start emitting enum shims
# wrapgen: end emitting enum shims
