name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Nim
      uses: iffy/install-nim@v5

    - name: Install Wayland compositor and client library
      run: |
        sudo apt-get update
        sudo apt-get install -y libwayland-client0 libwayland-egl1 libwayland-dev

    - name: Build
      run: |
        nimble install

    - name: Compile Wayland tests
      run: nim c tests/test1.nim
